### ISSUE TITLE
Why Zesty - Hybrid Solution Section Check Boxes

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#100]
https://kfg6bckb-dev.webengine.zesty.io/why-zesty/
Can we change these icons to match the icons in the screenshot below?

Current
![image](https://user-images.githubusercontent.com/101665566/158660863-ae305958-fc04-4dae-9f63-1a282777668f.png)

Change to:
![image](https://user-images.githubusercontent.com/101665566/158661086-689b6dd1-c686-430e-88b4-b2394b8d2e8d.png)

**Comment by darwin808** [comment]
both pictures are same

**Comment by Katiemoser** [comment]
Sorry, see below:
![image](https://user-images.githubusercontent.com/101665566/158664566-73efae6f-7b53-47da-b8e2-1a23676872a6.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_02-55-33](https://user-images.githubusercontent.com/71545960/158665965-172a66f1-d52e-4c1d-b743-b337321098c8.png)

**Comment by Katiemoser** [comment]
Approved.
