### ISSUE TITLE
Accounts: Instance Overview page needs clear instance cache button

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1035]
On the Instance Overview page the create instance button should be removed and a Clear Instance Cache should be added. It should fall on the same line as the instance name, placed on the right hand side

![Image](https://user-images.githubusercontent.com/50595614/190169222-902c459e-0fde-431e-8f24-8083162aa101.png)

**Comment by darwin808** [comment]
@bltarkany 
what should be the function of clear instance cache

**Comment by bltarkany** [comment]
@darwin808 I will slack you the endpoint that is hit for the clear cache function so that it is not exposed. This file in the manager-ui holds the functionality of the global navigation including the refresh instance cache:
https://github.com/zesty-io/manager-ui/blob/master/src/shell/components/global-instance/GlobalInstance.js
