### ISSUE TITLE
Accounts: Teams Page - if the instance has no team the table should remain but the interior should change

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1039]

**Comment by bltarkany** [comment]
On the Teams Page - if the instance has no team the table should remain but the interior of the table should show no column. 

Instead it should show a blank interior with the text: No Teams Added. And a button to add team. Similar to example below:




![Image](https://user-images.githubusercontent.com/50595614/190191013-dc9fbba9-2829-46aa-b255-131e76cd933e.png)
