### ISSUE TITLE
Accounts: APIs Page - Add read/write rest API & Webengine Mode documentation cards to the top of the page, API settings to the lower section, and documentation card to bottom of page

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1042]

**Comment by bltarkany** [comment]
On the APIs Page -- Create two cards above the table access token table:

>  the left card will provide documentation on our Read/Write Rest APIs
> log in options
> ways to access the APIs: Node SDK, direct rest APIs, fetch wrapper client side



> the right card will provide documentation on the Webengine Mode/GET APIs
> login options
> access levels
> webengine settings and effect


**Settings Section below Access token table:**

> Add Settings section below Access Tokens table. these settings will be to specific to API endpoint access and usage. listed below.

Add Learn more section below settings section:

> This will provide documentation on endpoint access levels, webengine modes. Along with learn more links 



**Settings Endpoint:**
https://instances-api.zesty.org/#66d6a878-5d9e-45f0-ac45-7adf1cf94d79

**Settings needed:**
- mode
- basic_content_api_enabled
- basic_content_api_cors_allow_any_origin
- ajax_cors_allow_any_origin
- gql
- gql_cors
- preview_lock_password
- headless_authorization_key
- authorization_key





![Image](https://user-images.githubusercontent.com/50595614/190264309-c20d4b8c-0570-4942-829c-e6b819dab075.png)



![Image](https://user-images.githubusercontent.com/50595614/190264337-29b0aaa1-01a7-418f-a5f7-3541031b07aa.png)
