### ISSUE TITLE
Accounts: Settings Page - remove the save column and added the save button

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1044]

**Comment by bltarkany** [comment]
On the settings page - remove the save button column from the table. And place the save button next to the setting adjustment similar to the domains page. A spacing treatment should also be added to the save buttons to create spacing between icon and text

**MUI button treatments:**
https://mui.com/material-ui/react-button/#buttons-with-icons-and-label

**Update to this layout:**


![Image](https://user-images.githubusercontent.com/50595614/190200596-12c529a3-8df4-43f0-bfb4-eb02e9a592c4.png)



**Remove Save column:**


![Image](https://user-images.githubusercontent.com/50595614/190201084-53ed6366-7719-49eb-85e0-a165ecd5ac53.png)
