### ISSUE TITLE
Accounts: Update Dashboard Page

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1061]
Updates to the Dashboard page:

**Left side navigation changes:**

 - remove the users name and `<hr>` below it.
 - change recent instances title to Your Instances
>  - change show more link to show all
 - shrink spacing between `<hr>` tags and titles
 - change Teams title to Your Teams
 - remove search input for teams section

**Center section changes:**

 - Title should Activity Stream
 - output 3 instances component cards - should be the users 3 most recently created instances
 - for the Timeline: using the users zuid get the users audit trail last action from their instances - up to 20
> -  icon for instances in the timeline will be the favicon on the instance
> -  continue editing button opens new tab that launches to the instance's content manager
> -  edit item button opens new tab that launches content manager to the specific item listed in audit

**Right side section:**

- 3 Cards along the right side
**Top card:**

>-  preview image grayed out mindshare background/hero image
>-  white text
>-  read article button to directs to article, in new tab
>-  article meta description as card content

**middle card**

>  - marketer call to actions 
>  - title, blurb button, 
>  - schema create in article

 
**Last card:**

>  - latest release notes
>  - latest release meta description
>  - button read latest release notes
> -  see all for release notes button

 

 remove timeline
 - comment it out
 

![Image](https://user-images.githubusercontent.com/50595614/190827125-dfb4a2ce-baf8-4be0-a22e-c3c0d94726ec.png)

**Comment by glespinosa** [comment]
Thank you @bltarkany , will work on this.

**Comment by giseleblair** [comment]
Right side Marketing cards:
1st card = latest article
2nd card= latest release notes
3rd card = marketing announcements

**Comment by giseleblair** [comment]
@bltarkany create a custom endpoint in main marketing instance that lists the items above ^^

**Comment by bltarkany** [comment]
@glespinosa endpoint for accounts dashboard cards:
the object has 3 keys:

- mindshare: for the mindshare card
- marketing: for the marketing card
- release-notes: for the release notes card

**instance file:**
https://8-aaeffee09b-7w6v22.manager.zesty.io/code/file/views/11-96f6d8afc4-9xzrct

**dev/preview url:**
https://kfg6bckb-dev.webengine.zesty.io/-/accountsdashcards.json

**production/live url:**
https://www.zesty.io/-/accountsdashcards.json
