### ISSUE TITLE
Website: in the marketplace, the install button needs to account for a Template entity type

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1093]
Example: https://kfg6bckb-dev.webengine.zesty.io/marketplace/templates/template-test/

The Install button uses logic based on 3 entity types: Module, App, or Extension. 
A 4th option needs to be added for the Template entity type. The install button for this type will direct the user to the Start app with a query parameter of the template item appended to the url.

**Comment by glespinosa** [comment]
@giseleblair 
### How do we determine that an item is a Template?
Right now these are the conditions in the code
![image](https://user-images.githubusercontent.com/44116036/192735686-14e1838c-c077-449b-a9af-e1edcc505726.png)
![image](https://user-images.githubusercontent.com/44116036/192735768-63e8b530-1293-4e63-986b-5c0a70bd4ef3.png)

**Comment by glespinosa** [comment]
Right now I'm checking the url if it has template
![image](https://user-images.githubusercontent.com/44116036/192764556-244f8ccb-8b40-4494-a3b4-cb9bab91887b.png)

And where we will redirect it?
![image](https://user-images.githubusercontent.com/44116036/192764673-90bf97f9-20ae-46c4-b56b-ca78aa5919ac.png)

**Comment by giseleblair** [comment]
Yes that is the correct way to check it @glespinosa

**Comment by giseleblair** [comment]
for the redirect,  please ask @darwin808
