### ISSUE TITLE
CSS all pages - iconography color

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#110]
Icons on all pages need to have background of Zesty Orange #FF5D0A

**Comment by Katiemoser** [comment]
David, to clarify - all the pages with the checkmark icons need to be Zesty orange #ff5d0a, not the current yellow color.

Example:
http://kfg6bckb-dev.webengine.zesty.io/solutions/headless-cms/
![image](https://user-images.githubusercontent.com/101665566/159077878-cdd09b89-6f0c-4e9e-9a1a-8e4200fc537e.png)

**Comment by d88naimi** [comment]
- [ ] TechnologyOverview Page :  http://zesty.io/solutions/headless-cms/
