### ISSUE TITLE
Beta Chip in Account Navigation

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#1114]
Use https://mui.com/material-ui/react-chip/ with danger color

Put in Navigation between the zesty logo and first link 

Update "create instance" in navigation to goto `/start/`

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/194347653-d6d68270-dfea-4e06-8603-11e0f0f370d5.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/194351451-2a5e5932-b8b6-4665-b732-9515c9ce20c2.png)
