### ISSUE TITLE
Accounts UI QA Needs

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#1115]
## NAv Buttons to Normal Size (they are small now)
![image](https://user-images.githubusercontent.com/729972/194352613-a58d231d-1000-4004-b3a4-5c0913a450ab.png)

## Navigation Border and Strange padding
![image](https://user-images.githubusercontent.com/729972/194355013-8040aa8c-714c-4876-9ab3-7f0e5d4842fe.png)
- Add permanent light gray border when crumbs are in the navigation
- Remove additional padding (this will fix alignment issue noted on crumbs)

## Crumbs colors
![image](https://user-images.githubusercontent.com/729972/194353631-cbcd998f-c364-4045-a6a6-60d11cbfd481.png)
change to 
![image](https://user-images.githubusercontent.com/729972/194354252-a6357135-9bc2-466a-b207-632519abe7ed.png)

- the slashes / are opacity .4
- the active link is font-weight normal, opacity .4
- The home button is the same as the link text color 

## Middle Aligning the Elements in Nav

![image](https://user-images.githubusercontent.com/729972/194352107-806ebd4f-2043-47a6-95dd-13be50db1b7e.png)

- Alignment Middle for Breadcrumbs 
![image](https://user-images.githubusercontent.com/729972/194352235-af4ad808-99fd-4aa5-9ca1-e2c920a7e41e.png)

- Alignment middle for navigation
![image](https://user-images.githubusercontent.com/729972/194351645-bc9ce5b3-c6af-41ea-989b-e800c76b1799.png)

**Comment by glespinosa** [comment]
![image](https://user-images.githubusercontent.com/44116036/194495705-58d1c955-4ced-4c07-a7a1-a509762727af.png)
