### ISSUE TITLE
Unable to View team members

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1125]
@dj-gaban-zestyio : transferring ticket to website repo for accounts

**Describe the bug**
- No results are being displayed upon viewing existing team member/s

**To Reproduce**
1. Go to: [Corporate Template](https://beta.zesty.io/instances/8-c8a8bba6bb-wqrplp/) or [STG_Instance](https://beta.zesty.io/instances/8-c4a7d2dccf-lbp2q4/)
2. Click on "Teams" on the left sidebar
![image](https://user-images.githubusercontent.com/114006998/194315862-4be31b94-2408-477d-b54a-17f3bd2c2232.png)
3. Click "View Team Members" of any team
![image](https://user-images.githubusercontent.com/114006998/194315427-8f1afade-351a-451b-80b5-eb658b88f4fb.png)
![image](https://user-images.githubusercontent.com/114006998/194315445-35bedb23-4b75-4274-b6fc-faa5589673ea.png)
-  If there's no existing team, please create one. [Reference](https://zesty.org/tools/guides/adding-a-team)
- If there's no existing team member, go to "Teams" in navbar, your team and click invite
![image](https://user-images.githubusercontent.com/114006998/194315332-f74b2024-bcd7-4b7a-a2d6-9ffbc069d873.png)

4. See that no results are displayed
![image](https://user-images.githubusercontent.com/114006998/194315496-132f6451-0100-4ba3-a3b0-c03118f6d646.png)
![image](https://user-images.githubusercontent.com/114006998/194315506-5c070dd2-a6b1-4566-96a6-4536014ab5bd.png)

**Additional context**
- Existing member's info should be displayed

**Additional context**
In some instance/s like: [Acme Recipes](https://beta.zesty.io/instances/8-a6c8bb86e2-mzdf9l/), members are being displayed.
![image](https://user-images.githubusercontent.com/114006998/194316404-d2708779-7a44-47c2-80ad-a3f18306292b.png)

**Comment by darwin808** [comment]
@bltarkany 

I can view team member on other instance 

![image](https://user-images.githubusercontent.com/71545960/194546443-dc487b95-09ea-4410-99f9-ee229cffe78e.png)

**Comment by bltarkany** [comment]
@darwin808 it is not consistent. I've added you to my onboarding project so you can see one that isn't working. 
legacy: https://accounts.zesty.io/instances/8-c0ada7edaf-lm0bh4
beta: https://beta.zesty.io/instances/8-c0ada7edaf-lm0bh4/

I have members in both of the teams listed but the members do not display in the ui:
65-8efafaf7c8-dqtfz9
65-fc89accb8f-v40tlq
![image](https://user-images.githubusercontent.com/50595614/194585150-fd4ca593-9567-469d-b10e-3a02217b30dd.png)
![image](https://user-images.githubusercontent.com/50595614/194585165-29d23cb8-026b-4b61-ad43-fff53daac98d.png)
![image](https://user-images.githubusercontent.com/50595614/194585193-6a7537a4-3b15-4d36-aea7-b9ac18dfc88d.png)

**Comment by darwin808** [comment]
@bltarkany 

upon checking the legacy it does not contain team members 

![image](https://user-images.githubusercontent.com/71545960/195058712-d63dad37-1bc3-426d-8b22-5e436ec5b07b.png)

**Comment by giseleblair** [comment]
The team members should also include the team owner

**Comment by bltarkany** [comment]
for each of these teams there is one additional member beside the owner - which can be seen in the teams page:
![image](https://user-images.githubusercontent.com/50595614/195122671-05d800c6-8445-4f32-b678-37f9043a54e1.png)
![image](https://user-images.githubusercontent.com/50595614/195122708-7a8e3cef-7b72-4e31-8712-8ef825982cd4.png)
