### ISSUE TITLE
Error message on Profile view

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1127]
Go to: https://beta.zesty.io/profile/

See error message

![Image](https://user-images.githubusercontent.com/9896546/194418791-4c8557d3-10d5-45d1-91d4-2c7bf17ad86e.png)

**Comment by darwin808** [comment]
@giseleblair 

is this for newly created account or old one? Im trying to replicate it on my end

**Comment by darwin808** [comment]
@giseleblair https://github.com/zesty-io/website/issues/1123
