### ISSUE TITLE
Added domains doesn't load or display

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1129]
@dj-gaban-zestyio : transferring ticket to website repo for accounts

**Describe the bug**
After adding a domain, it doesn't load or display upon launching the website

**To Reproduce**
1. Go to any instance/s
2. Click on 'Add domain'
![image](https://user-images.githubusercontent.com/114006998/194137000-d150c5c1-3ec9-4eb7-bb42-7a4950a7c946.png)

3. Input the "Domain" and "Branch" then submit
![image](https://user-images.githubusercontent.com/114006998/194137102-f778faa3-2fa1-4a3d-a6dc-d75e81fa443a.png)

4. Click the recently added domain
![image](https://user-images.githubusercontent.com/114006998/194137262-4815aef8-4120-4cad-8683-e1a40d1ad689.png)

5. See error
![image](https://user-images.githubusercontent.com/114006998/194137326-515c7c26-828c-4e3e-8e84-46ed173ca261.png)

**Comment by darwin808** [comment]
@bltarkany 

im using the `createDomain ` from fetchwrapper to add domain , can you also verify it thanks

**Comment by bltarkany** [comment]
@darwin808 the `createDomain`  from the fetchwrapper is correct.

I reviewed the workflow that James used for the bug he reported above. Based on that information the way he formatted the url on creation was incorrect - not the `createDomain` function. 

I tested the creation of both a live and dev vanity domain url with no issue. this looks to be resolved
