### ISSUE TITLE
Unable to make selection or change WebEngine Mode setting

### ISSUE THREAD

**Issue by smserpa** [zesty-io/nextjs-website#1132]
Dropdown menu for WebEngine Mode in settings does not have a selection option -Stef

Loom: https://www.loom.com/share/cbe1548fadfb440494406e7e83ab611b

I am able to save but it's not reflecting on instance - Gisele

Loom: https://www.loom.com/share/02a66b86b08849f4b2c3db04f5e97294

**Comment by darwin808** [comment]
@smserpa can you try again in https://beta.zesty.io/ thanks
