### ISSUE TITLE
Instance Settings: Group by Setting Type

### ISSUE THREAD

**Issue by smserpa** [zesty-io/nextjs-website#1133]
"Enable Canonical Tag" Setting should follow "Content Set ID override for /feed.xml" 

Setting for seo settings to be grouped? 

Also "GraphQL endpoints" and "GraphQL Cors" should be with other developer settings

**Comment by darwin808** [comment]
@smserpa 

`seo` are group like below 

![image](https://user-images.githubusercontent.com/71545960/194530118-31408e9d-cd1e-4a2b-a14c-14d489ada6dd.png)

`grapql` are also in developer settings 

![image](https://user-images.githubusercontent.com/71545960/194530228-4edcf7f3-39aa-4334-900f-f72adc7f7209.png)
