### ISSUE TITLE
Cannot Rename an Instance

### ISSUE THREAD

**Issue by gtllien** [zesty-io/nextjs-website#1147]
I'm not seeing any option to Rename an Instance in the New Accounts UI.

Here's a video for reference: https://www.loom.com/share/1929f06b2ed84271952d7b5950641e28

**Comment by giseleblair** [comment]
https://www.loom.com/share/9330b376ca2b42fba6f5ec09b7fc42cd

**Comment by glespinosa** [comment]
@giseleblair closing this now since it resolved by doing hard refresh. Thank you!
