### ISSUE TITLE
Cannot Delete Ecosystem

### ISSUE THREAD

**Issue by gtllien** [zesty-io/nextjs-website#1148]
**Describe the bug**
I deleted an instance but the ecosystem still exist and cannot be deleted

**To Reproduce**

- Go to Instances view
- Click on Select Ecosystems
- See the options in the dropdown selection, and it still has the Demo Site2 in which I already deleted its Instance (Deleted Instance Name: Demo Site2).
- Tried deleting the Ecosystem ZUID: "35-daaf9de7ee-b10tqk" via API but an error "_Forbidden Action_" occurred

**Expected behavior**
An expected behaviour would be that the Ecosystem (that was automatically created along with the Instance) should also be automatically deleted when the Instance is deleted.

Ecosystem ZUID: "35-daaf9de7ee-b10tqk"

**Comment by darwin808** [comment]
@gtllien base on figma we dont have delete ecosystem in ui , can you also confirm thanks 

https://www.figma.com/file/6JdMdepU9BIH6gSvxAfOjW/Accounts-Revamp?node-id=28%3A598

**Comment by gtllien** [comment]
@darwin808 
Yes. There's no option to delete an ecosystem in the UI.
