### ISSUE TITLE
Ecosystem with no Instance/s added is displaying all Instances in view

### ISSUE THREAD

**Issue by gtllien** [zesty-io/nextjs-website#1149]
I added a new Ecosystem via API (Test Ecosystem1) but did not add any Instance to it yet.
When I browsed to the Instances view page, selected the specific Ecosystem under the Select Ecosystems dropdown, I got ALL Instances displayed which should not be the case since the specific Ecosystem I created via API doesn't have any Instance added to it yet so it should not display any Instances in view unless I add one.

Ecosystem Name: Test Ecosystem1
ZUID: 35-d6b786e596-fl5fr0

Here's a video for reference: https://www.loom.com/share/ce2ad4af51c745c6978e5362c682fc0f

**Comment by darwin808** [comment]
https://github.com/zesty-io/website/issues/1148
