### ISSUE TITLE
User View of an instance does not show pending users and no ability to cancel pending invite

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1154]
In beta the users view does not show the pending users of an instance and does not allow for pending users to be canceled. 

legacy accounts:

![Image](https://user-images.githubusercontent.com/50595614/194860145-eef1558a-45e6-44cb-b138-d89652c9e1b0.png)

Beta accounts:

![Image](https://user-images.githubusercontent.com/50595614/194860200-fafb6d96-1ea4-40af-bff4-e650ae6f978c.png)

**Comment by darwin808** [comment]
@bltarkany 

![image](https://user-images.githubusercontent.com/71545960/194873493-a97aa10c-c801-4b60-99e4-831e2710f96e.png)
