### ISSUE TITLE
marketing card button on accounts overview page needs content from the cta_text key in the json output

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1175]
On the accounts Dashboard page - the marketing card button needs the `cta_text` content from the json endpoint:

https://kfg6bckb-dev.webengine.zesty.io/-/accountsdashcards.json

```

"marketing": {
"title": "Integrate your Favorite Technology with Zesty",
"description": "The Zesty.io Marketplace features top integrations and tools, such as Live Editor and Layouts, to help you create and distribute content faster.",
"cta_text": "Go to Marketplace",
"link_type": "external",
"url": "https://www.zesty.io/marketplace"
}

```

![Image](https://user-images.githubusercontent.com/50595614/195426774-44715946-0fef-42e5-b2fc-60d0474d589c.png)

**Comment by glespinosa** [comment]
Thanks @bltarkany will work on this
