### ISSUE TITLE
Why Zesty - Articles broken at bottom

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#120]
https://kfg6bckb-dev.webengine.zesty.io/why-zesty/

Articles boxes not rendering

![image](https://user-images.githubusercontent.com/101665566/158702251-89baa251-f307-4603-bd98-374331c2a37f.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_15-12-02](https://user-images.githubusercontent.com/71545960/158756051-ae62421e-8ed8-4e14-bbd7-6df5977179b7.png)

this is link to blogs section and i get no data in endpoint  @giseleblair
