### ISSUE TITLE
with virtualization in place, the search function does not display all results

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1216]

**Comment by glespinosa** [comment]
Hi @giseleblair , we tested it when searching, it shows all possible results base on search. Below is the demo

[screencast-meet.google.com-2022.10.20-17_27_59.webm](https://user-images.githubusercontent.com/44116036/196911859-16fa1b47-0303-4264-9266-355e76a14490.webm)

- Can I see it on your part what's happening? Thank you
