### ISSUE TITLE
A/B Landing Page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#1224]
Landing page template: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-beb393cb89-4dl2n5/7-facfcbf68b-zpl8tj
Variations: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-aa81a983e2-k9mzjm
Doc outline: https://docs.google.com/document/d/1AG7LA345wWDG-yOeqX6UAyAuGpZuGcU2dEQaOSl9rDI/edit?usp=sharing

Please create a landing page with the following components:

**Header**
From: https://www.zesty.io/ppc/content-management-system/ 

- Make secondary button like the homepage secondary button

![image](https://user-images.githubusercontent.com/101665566/197048485-7dab273e-8d3b-4541-a4ad-168f8e3dec24.png)

**Logo bar from homepage with H2**
![image](https://user-images.githubusercontent.com/101665566/197048728-3ccd9b8b-36e2-4a24-8334-0d0b167408a9.png)

**H2 from homepage**
![image](https://user-images.githubusercontent.com/101665566/197048972-2ef76ce1-a2da-4190-98c7-f60cdfca7f14.png)

**Benefits section from homepage**
![image](https://user-images.githubusercontent.com/101665566/197048895-68832f38-e457-4f4d-8faf-bd8f822e9bbe.png)

**Middle CTA from homepage**
![image](https://user-images.githubusercontent.com/101665566/197049116-1e70ec5a-b658-4676-8214-ca2a22ba53d6.png)

**Features** 
From: https://www.zesty.io/ppc/content-management-system/ 
![image](https://user-images.githubusercontent.com/101665566/197049315-15c1a5f7-2818-43e6-8bc1-bf931080cf46.png)

**Testimonial**
From: ./src/blocks/team/WithCompanyLogo/WithCompanyLogo.js|ts

- Don't need logo

![image](https://user-images.githubusercontent.com/101665566/197049590-96fe2737-2a49-4fd7-b32b-7147399c688b.png)

**Final CTA**
![image](https://user-images.githubusercontent.com/101665566/197049116-1e70ec5a-b658-4676-8214-ca2a22ba53d6.png)

**Comment by jomarmontuya** [comment]
deployed on stage  -> https://kfg6bckb-dev.webengine.zesty.io/discover
