### ISSUE TITLE
Why Zesty - "modern development process" image

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#123]
https://kfg6bckb-dev.webengine.zesty.io/why-zesty/
Please remove this image from the code (where it says "missing content)

![image](https://user-images.githubusercontent.com/101665566/158706649-a60e2fd0-b719-43d5-9cbd-903b4dcb2945.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_15-06-03](https://user-images.githubusercontent.com/71545960/158755028-5b4be859-d026-404f-8568-b9667fd5d813.png)
