### ISSUE TITLE
zesty.io and accounts login not loading properly

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1271]
Behavior seen by user:

> i've been having this issue with the Zesty.io site for a couple weeks now (since the new design was launched). I'm finally having some free time that I could look at it more. Doing my usual cache clearing doesn't work. If I open a new incognito window the site appears to be fine. Deleted all the cookies, etc, still getting broken site.

**Users images -- Add'l info below:**

![image](https://user-images.githubusercontent.com/50595614/199113164-175ad12c-e99b-430c-83a7-dd3c8d4897a6.png)
![image](https://user-images.githubusercontent.com/50595614/199113137-4d0ffc11-d594-476b-ae1a-99725de6cc58.png)

**Unable to replicate broken render but can see console errors:**

when testing I am able to see the errors seen by user, but I am unable to see the broken rendering state. The user is able to log into legacy accounts but it directs to a 404 if the user tries to use the try new accounts button. Please see thread for user workflow video:
https://zesty-io.slack.com/archives/C050120G5/p1667239379964919

my console errors when testing
![image](https://user-images.githubusercontent.com/50595614/199113709-cfd03023-39be-47fc-ab4c-2f15e0ddea9b.png)

**Comment by jomarmontuya** [comment]
Additional information 

I'm getting the same rendering issue when I try to access the website on my computer same work computer but different browser profile

Clear page cache still the same, but works fine on incognito 

![image](https://user-images.githubusercontent.com/61284357/199119150-b26fdf80-b1f7-49a2-9035-bf0b32341876.png)

networks errors that might be helpful 

![image](https://user-images.githubusercontent.com/61284357/199119430-12ebc2f3-c05e-4641-89b4-6b4390230187.png)

![image](https://user-images.githubusercontent.com/61284357/199119544-de563c79-360b-42bb-84af-af4e054c8443.png)

Did some troubleshooting on my end and in my case two of chrome extension causing rendering issues

**Comment by darwin808** [comment]
> Additional information
> 
> I'm getting the same rendering issue when I try to access the website on my computer same work computer but different browser profile
> 
> Clear page cache still the same, but works fine on incognito
> 
> ![image](https://user-images.githubusercontent.com/61284357/199119150-b26fdf80-b1f7-49a2-9035-bf0b32341876.png)
> 
> networks errors that might be helpful
> 
> ![image](https://user-images.githubusercontent.com/61284357/199119430-12ebc2f3-c05e-4641-89b4-6b4390230187.png)
> 
> ![image](https://user-images.githubusercontent.com/61284357/199119544-de563c79-360b-42bb-84af-af4e054c8443.png)
> 
> Did some troubleshooting on my end and in my case two of chrome extension causing rendering issues

what is the chrome extension @jomarmontuya

**Comment by jomarmontuya** [comment]
@darwin808 

Chrome extension causing error on my end is 
-Ronin Wallet
-WagmiSwap Wallet 

This are all crpyto wallets I have. If this extensions enabled zesty website don't load correctly. I don't know what's with this causing issues on our site
