### ISSUE TITLE
Roadmap page error

### ISSUE THREAD

**Issue by glespinosa** [zesty-io/nextjs-website#1276]
![image](https://user-images.githubusercontent.com/44116036/199495756-8b300c24-5f7c-47de-8b07-8d111efe3588.png)

**Comment by ardeay** [comment]
![image](https://user-images.githubusercontent.com/729972/199822760-933767e8-c30a-45f8-b854-444f579f3bac.png)
@jomarmontuya this runs locally, but with errors, please address it tomorrow.

**Comment by jomarmontuya** [comment]
Closing this issue as resolved
