### ISSUE TITLE
Marketplace 404

### ISSUE THREAD

**Issue by glespinosa** [zesty-io/nextjs-website#1314]
404 errors on slug urls for marketplace

![Screenshot_20221105-193853](https://user-images.githubusercontent.com/44116036/200118079-2bad6395-e616-4362-96c9-0de79241dd29.jpg)

**Comment by ardeay** [comment]
this is resolving https://www.zesty.io/marketplace/

please provide example urls that are failing @glespinosa , thank you!

**Comment by glespinosa** [comment]
Links that were failing

https://www.zesty.io/marketplace/:slug
-https://www.zesty.io/marketplace/apps/
-https://www.zesty.io/marketplace/templates/
-https://www.zesty.io/marketplace/modules/
-https://www.zesty.io/marketplace/extensions/

also those specific pages like:
https://www.zesty.io/marketplace/apps/google-analytics/
