### ISSUE TITLE
Darkmode layout problem in Products Page when in large screen size

### ISSUE THREAD

**Issue by glespinosa** [zesty-io/nextjs-website#1326]
Headless CMS Page (/solutions/headless-cms/)
Hybrid CMS (/solutions/hybrid-cms/)

![image](https://user-images.githubusercontent.com/44116036/200597366-bb4d5481-53ca-41eb-90a7-57b1ff351947.png)
![image](https://user-images.githubusercontent.com/44116036/200597454-3c7351ee-5318-4ad2-8e89-0e7417906f42.png)

Repetition of background
Solutions (/solutions)
![image](https://user-images.githubusercontent.com/44116036/200598392-d856da67-89b2-4fb9-a01b-067d9450dfe0.png)

Having scrolling when large screen size and same issues above
Digital Experience Platform (solutions/digital-experience-platform/)
![image](https://user-images.githubusercontent.com/44116036/200599586-cae94499-3cfb-4003-a048-c327dcee7f3e.png)

Integrations Menu doesn't have attached link / page to it?
![image](https://user-images.githubusercontent.com/44116036/200601052-ef87b47b-8115-4a34-9ff3-d753bce6e8ab.png)

DXP Enterprise (/solutions/digital-experience-platform/dxp-enterprise/)
![image](https://user-images.githubusercontent.com/44116036/200601829-b60e6328-0ac6-475b-98a9-9b8bd37c1421.png)

When in darkmode the text disappears
![image](https://user-images.githubusercontent.com/44116036/200602071-f31e63e7-0482-418c-a950-0e63b23d7d4b.png)

**Comment by jomarmontuya** [comment]
https://github.com/zesty-io/website/pull/1357

PR is open for the issue

Integrations Menu doesn't have attached link / page to it? -> I will connect with katie to remove it from the navbar for now
