### ISSUE TITLE
Subscribe div getting consume by the background above when in large screen size

### ISSUE THREAD

**Issue by glespinosa** [zesty-io/nextjs-website#1329]
https://www.zesty.io/blog/
https://www.zesty.io/news/
https://www.zesty.io/mindshare/customer-stories/

[screencast-www.zesty.io-2022.11.08-23_25_12.webm](https://user-images.githubusercontent.com/44116036/200606256-dc152461-62d6-437c-be6d-902704b08083.webm)

**Comment by jomarmontuya** [comment]
https://github.com/zesty-io/website/pull/1349
