### ISSUE TITLE
Headless CMS/Tech Overview - connect logo

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#133]
@darwin808 

https://kfg6bckb-dev.webengine.zesty.io/solutions/headless-cms/
Please connect the "testimonials logo" section in schema to code so it shows the Sony logo.

![image](https://user-images.githubusercontent.com/101665566/158863064-1777a899-f824-4235-b487-333dd5e107c8.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-18_01-49-49](https://user-images.githubusercontent.com/71545960/158864420-398ac40c-3cbc-44ac-a086-5e361489f6e3.png)

**Comment by Katiemoser** [comment]
Thank you!
