### ISSUE TITLE
Footer parent link misaligned 

### ISSUE THREAD

**Issue by jomarmontuya** [zesty-io/nextjs-website#1345]
![image](https://user-images.githubusercontent.com/61284357/201104406-3b44c105-c7cb-4fc5-9fe8-eec3aa22a234.png)

**Comment by glespinosa** [comment]
@jomarmontuya saw this also when checking it in mobile.. Is your solution same as this ? https://github.com/zesty-io/website/pull/1352
my commit on this pr: https://github.com/zesty-io/website/pull/1352/commits/e65c11ed0d489520cb3006305e49cfe614b409da

**Comment by jomarmontuya** [comment]
Haven't touched it yet but seems your PR solved the problem. Closing this now @glespinosa  thank you!
