### ISSUE TITLE
"http" urls  not automatically redirecting to "https"

### ISSUE THREAD

**Issue by jeromeZestyIO** [zesty-io/nextjs-website#1363]
"http" not automatically redirecting to "https"

![Screenshot 2022-11-15 003550](https://user-images.githubusercontent.com/115722439/201715265-3daaaaef-1cee-4a6e-af98-f711dacbf6f5.png)

**Comment by glespinosa** [comment]
Duplicate of this https://github.com/zesty-io/website/issues/645
