### ISSUE TITLE
Headless CMS - Icons & image broken

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#137]
@darwin808 
https://kfg6bckb-dev.webengine.zesty.io/solutions/headless-cms/
See below

![image](https://user-images.githubusercontent.com/101665566/158870557-73329766-c0ad-476c-8c9f-1d45466f72d6.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-18_02-41-48](https://user-images.githubusercontent.com/71545960/158873520-f6d66eb0-85c8-4918-a4d9-b5de6cd217da.png)
i didnt merge or pr in main , this pic is only in my local
