### ISSUE TITLE
/solutions/ header needs to render HTML

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#138]

**Comment by bltarkany** [comment]
looks like logic was added in another devs pr for this, do you still want me to change it? it is outputting correctly
![image](https://user-images.githubusercontent.com/50595614/158904379-86eca5ed-39b6-488e-a8d8-f953de59f4c2.png)
![image](https://user-images.githubusercontent.com/50595614/158904417-cca1f614-7e3e-4748-9038-4b32915a36c3.png)

**Comment by ardeay** [comment]
cool, im closing issue
