### ISSUE TITLE
Website: Accounts General feedback on instance

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/nextjs-website#1402]
:point_down:  feedback notes in screenshot
![image](https://user-images.githubusercontent.com/208819/203635398-9e72b932-4bcd-448d-a11a-214818fd9bf9.png)

**Comment by glespinosa** [comment]
@zcolah @ardeay 

What to display when the "?" Icon got hover and text below Domain?

All of the page has this pattern not only the Domain page.

**Comment by ardeay** [comment]
@bltarkany Please provide information to go in the overlays that explain what each thing is for each you
