### ISSUE TITLE
Github SSO button 

### ISSUE THREAD

**Issue by mattezra** [zesty-io/nextjs-website#1404]
**Is your feature request related to a problem? Please describe.**
We need a Github SSO button in Accounts-UI login similar to how Google SSO button was implemented

**Describe the solution you'd like**
A button with a link to these endpoints that is based upon the environment:

1. https://auth.api.dev.zesty.io/github/login
2. https://auth.api.stage.zesty.io/github/login
3. https://auth.api.zesty.io/github/login

**Additional context**
[Project board](https://github.com/orgs/zesty-io/projects/75/views/4)
[Tech Spec](https://docs.google.com/document/d/1iEK9f9AoSGfPfBcRNuJOEBJ0iciBXDaivxIcMSsszK4/edit)

@darwin808 Let me know if there's any questions. Tagging @zcolah and @shrunyan here as well.

**Comment by mattezra** [comment]
@darwin808 

If the github user has no name in [github public profile page](https://github.com/settings/profile), this error is being returned: 
`{"message":"Name of Github account has not been set.","status":"Bad request","data":null,"meta":{},"code":400}`

Could this be handled by the UI to show this error message?

**Comment by mattezra** [comment]
@shrunyan 

Tagging you here. See my comment above, UI needs to handle the error `{"message":"Name of Github account has not been set.","status":"Bad request","data":null,"meta":{},"code":400}` which occurs when the github user has no name in [[github public profile page](https://github.com/settings/profile)](https://github.com/settings/profile).

Can you advise the best way to handle this error in the UI?

**Comment by darwin808** [comment]
@mattezra @giseleblair @ardeay 

Im getting an error in  https://beta.zesty.io/

![image](https://user-images.githubusercontent.com/71545960/211592159-f8f94065-0043-46fd-af1d-a45a4d474540.png)

**Comment by mattezra** [comment]
@darwin808 @giseleblair @ardeay 

I tested this and confirmed that it has been fixed when the env var was added to prod. 

Can you test again?
