### ISSUE TITLE
Marketplace Experience: Inform user which instance the app gets added to

### ISSUE THREAD

**Issue by zcolah** [zesty-io/nextjs-website#1431]
I was using the marketplace experience and clicked on install app and it told me the app was installed. However I did not know which instance the app is installed to. One of my instances had the app installed while the others did not and this was confusing to me as a user.

May we add some form of message to a user that informs them which instance was the app installed to?

**Comment by ardeay** [comment]
@darwin808 @zcolah 
![image](https://user-images.githubusercontent.com/729972/205951961-f2f19ee5-3813-4348-920f-6d14faa47af7.png)
