### ISSUE TITLE
Join App user flow 

### ISSUE THREAD

**Issue by darwin808** [zesty-io/nextjs-website#1437]
# User flow in Join app 

### Business Lead 

https://user-images.githubusercontent.com/71545960/206351985-383c8ab0-f6f4-4860-8ae2-994543a018e6.mp4

### Dev Lead 

https://user-images.githubusercontent.com/71545960/206351990-dcd25d48-2a68-435c-b380-df039b44a7ce.mp4

### Market Lead 

https://user-images.githubusercontent.com/71545960/206351999-bc66bc6f-4e87-483d-b733-3c2cc0146bda.mp4

### Project Manager 

https://user-images.githubusercontent.com/71545960/206352003-f5754dda-19a5-4f73-a5a3-8c33ac92275c.mp4

### Product Manager 

https://user-images.githubusercontent.com/71545960/206352006-e106bb2f-9089-4b00-8c3f-cc43e9fd8f9d.mp4

## Developer + personal 

https://user-images.githubusercontent.com/71545960/206352078-fea1fbe7-c651-469c-95a0-405faec150ed.mp4

## Developer + business 

https://user-images.githubusercontent.com/71545960/206352098-0869c392-2f7e-4561-887a-6ef419d77fc5.mp4

## Marketer personal 

https://user-images.githubusercontent.com/71545960/206352129-1861cf01-a5b5-49d5-8da3-afb93b37ae57.mp4

## Marketer business 

https://user-images.githubusercontent.com/71545960/206352151-5ebebdfe-5302-437d-b4af-bbfd41fbc771.mp4

## Content Creator + personal 

https://user-images.githubusercontent.com/71545960/206352178-1cfee8bf-b199-4327-ad15-7eb91c184ef3.mp4

## Content Creator + business 

https://user-images.githubusercontent.com/71545960/206352215-0204f938-4df7-4f99-a381-a25446db0da9.mp4

**Comment by ardeay** [comment]
Confirmed data for each flow @darwin808 @toddsabo 

- [ ] Decision maker flow: data to zoho
- [ ] Personal flow: data to zoho
- [ ] Business maker flow: data to zoho
