### ISSUE TITLE
Pricing Page - Table

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#147]
- Table columns change depending on how long "Features" lines are - can we make these fixed all the way down and wrap text in the features line if need be?
- Tables are coming in random order - can we implement a way to order them custom?
- There is no "apps" section - need to add
- Rows are not following sort order
- Please also make all headers title case and bolded instead of all caps. Ensure font sizes are the same.

![image](https://user-images.githubusercontent.com/101665566/158908754-1c639661-a3ca-4174-bc7a-7f7227d06d11.png)

**Comment by giseleblair** [comment]
@Katiemoser new classification items can be added in Schema for Pricing Levers. Add a new item in the Classifications dropdown
