### ISSUE TITLE
Pricing Page - pricing cards

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#148]
Make 4 across instead of 3 and 1 below

![image](https://user-images.githubusercontent.com/101665566/158908932-f7796acb-fe9f-4c4a-a213-e00a03160ee5.png)

**Comment by Katiemoser** [comment]
Additionally:
- Buttons aren't pulling from content manager
- Not all content is syncing correctly
- Need more bullet points (see schema)
- If left blank, need button to not show up like it is on "free"
- The 1 instance bullet looks like it must be hard coded - can we please remove?

**Comment by giseleblair** [comment]
Per @ardeay 's direction, the CTA buttons are all triggering the TryFree CTA component. 
All list content is dynamic, if there are edits that are not displaying, please link the content item and reference the field that is not properly displaying. 
Schema is not dynamically added to pages. If new schema fields are added to a content model, please coordinate with a dev to have that display properly on a page. 
I have added conditional logic that will not display list item if left blank. (this will display in preview after my next merge)
