### ISSUE TITLE
Pricing - header

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#149]
Subtitle not rendering

![image](https://user-images.githubusercontent.com/101665566/158908968-3d237890-a235-488e-8986-ab2c9e3f6cc5.png)

**Comment by giseleblair** [comment]
@Katiemoser 
It looks like the textfield's Field Name was changed from "subtitle" to "instance_definition". If Field Names are renamed, that will break the reference in the code. You are free to change the Field Label of any fields but if you change any Field Names you'll need to coordinate with a developer before doing so or it will break production content.

**Comment by Katiemoser** [comment]
Okay good to know, thanks!
