### ISSUE TITLE
404 page loads old design

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/nextjs-website#1550]
![image](https://user-images.githubusercontent.com/208819/212173864-255c44ff-e273-4308-b177-9e820a31f8a1.png)

**Comment by jeromeZestyIO** [comment]
Hi @shrunyan,

Just like to ask where does the link [https://www.zesty.io/next/](https://www.zesty.io/next/) came from?

Here are some pages related to nextjs:
https://www.zesty.io/integrations/nextjs-cms/
https://www.zesty.io/integrations/nextjs-team-benefits/

Thanks!

**Comment by shrunyan** [comment]
Any update on this issue?

**Comment by jeromeZestyIO** [comment]
@shrunyan we're looking into it. possible same issue with:
https://github.com/zesty-io/website/issues/674
