### ISSUE TITLE
Add Learn and other documentation tools into the header Documentation tab in accounts

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#1551]
**Enhancement request from client**
When logged in, some of the menu items from the home page are no longer shown. Most of these are marketing related items - and as a user  the assumption is if I'm logged in I don't need to be marketed to anymore.
For example:
Today I find myself needing to pull up a blog article that has something I need that hasn't been added to the documentation yet. The blog is under the **"Learn"** menu but that isn't shown for logged in users. There are use cases where users want and need to get to any of these **"learn"** and **"more"** items.

**When logged out dropdown options:**

![image](https://user-images.githubusercontent.com/50595614/212347232-589972b5-37b1-49a1-9c78-147080845827.png)

![image](https://user-images.githubusercontent.com/50595614/212347153-4f998001-2d35-4f9a-8951-3771321b0ce9.png)

**when logged in dropdown options:**

![image](https://user-images.githubusercontent.com/50595614/212347390-adcf7130-3a6e-4659-841b-17d598b507c5.png)

**Comment by darwin808** [comment]
@bltarkany there is an update in navigation see https://github.com/zesty-io/website/pull/1415

**Comment by jomarmontuya** [comment]
confirm resolution based on the #1415
