### ISSUE TITLE
Navigation Bar: API Docs in the Top Navigation Menu Learn section links only to Authentication API

### ISSUE THREAD

**Issue by zcolah** [zesty-io/nextjs-website#1561]
The API Docs in the Top Navigation Menu Learn section links only to Authentication API. It should instead link to the Instances API. 

<img width="1440" alt="Screenshot 2023-01-17 at 5 12 29 PM" src="https://user-images.githubusercontent.com/22625919/213056452-e4e799e8-c895-47f5-ae07-d3cd3b8cf984.png">

**Comment by jeromeZestyIO** [comment]
hi @zcolah, 

Just to confirm, is this the link we should put? 
https://zesty.org/apis/instances-api

Thanks!

**Comment by jomarmontuya** [comment]
@jeromeZestyIO  can you confirm if we can close  this?

**Comment by jeromeZestyIO** [comment]
@jomarmontuya I already updated the link to [https://zesty.org/apis/instances-api](https://zesty.org/apis/instances-api). We can now close this.
