### ISSUE TITLE
homepage h1

### ISSUE THREAD

**Issue by tomseodirect** [zesty-io/nextjs-website#162]
![image](https://user-images.githubusercontent.com/101887142/159040648-053c9e73-2648-47ac-a7b7-a7672b7cc7bf.png)

**Comment by Katiemoser** [comment]
@d88naimi - can you address the second portion of the screenshot? We need "The power of Zesty's headless CMS" to be an H2 (keep current CSS styling)

This is actually on the "headless CMS page" : https://kfg6bckb-dev.webengine.zesty.io/solutions/headless-cms/
