### ISSUE TITLE
CSS Why Zesty - header

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#172]
http://kfg6bckb-dev.webengine.zesty.io/why-zesty/
Please drop font size down on "why Zesty" H1 to match the size of the "powerful digital solutions" H1 on solutions page: http://kfg6bckb-dev.webengine.zesty.io/solutions/

**Comment by Katiemoser** [comment]
Please also change color of "why zesty" to grey to match the homepage: #677788

**Comment by d88naimi** [comment]
Dropped fontsize to 20 like solutions page 

![Screen Shot 2022-03-18 at 5 25 58 PM](https://user-images.githubusercontent.com/22800749/159099319-eeffe934-fafd-410b-a51b-2a1d599b9934.png)
