### ISSUE TITLE
Page optimization and core web vitals

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#1761]
Please improve the suggestion on this including

- crawlable links
- javascript optimization
- check the double entry of google tag manager
- Check the double addition of pagesense (zoho) is this through tag manager?

Make changes core web vitals pass
![image](https://github.com/zesty-io/website/assets/729972/8a8c4ede-66f4-4571-902e-dd2929d21f60)

https://pagespeed.web.dev/analysis/https-www-zesty-io/2mktroflzh?form_factor=desktop

**Comment by ardeay** [comment]
This link to contact us is not working 
![image](https://github.com/zesty-io/website/assets/729972/e1271eec-5de1-4384-8f39-9ae05fa8702f)

**Comment by ardeay** [comment]
![image](https://github.com/zesty-io/website/assets/729972/ab2cc502-51d8-4a6c-afe6-a27bd9975b01)

GTAG manager loading twice?

**Comment by ardeay** [comment]
![image](https://github.com/zesty-io/website/assets/729972/98109f54-32d7-40e1-9b28-93a6d4163598)
is the correct one. It looks like we may be doing this correctly: 

![image](https://github.com/zesty-io/website/assets/729972/de2e966c-97b4-42df-91f7-51de201ac098)

**Comment by darwin808** [comment]
> ![image](https://user-images.githubusercontent.com/729972/240354330-ab2cc502-51d8-4a6c-afe6-a27bd9975b01.png)
> 
> GTAG manager loading twice?

we only have one gtag `GTM-MSPH3C8`

**Comment by darwin808** [comment]
> This link to contact us is not working ![image](https://user-images.githubusercontent.com/729972/240353985-e1271eec-5de1-4384-8f39-9ae05fa8702f.png)

this is resolved
