### ISSUE TITLE
Ticket created through Support portal has value "Phone" as its Channel

### ISSUE THREAD

**Issue by gtllien** [zesty-io/nextjs-website#1834]
Request to update the **Channel** value for tickets created via Support portal.
Current value is "Phone" which should be updated since the source is not coming from phone

Screenshot of a sample ticket created:
![image](https://github.com/zesty-io/website/assets/112954373/dee2dc05-e94b-4051-b40e-fd6f3a37ca0b)

**Comment by jomarmontuya** [comment]
@gtllien  can you help me confirm if this issues still exist in zoho?

**Comment by gtllien** [comment]
@jomarmontuya 

Issue still exist - when a new ticket is created through Support portal the Zoho field channel displayed is "Phone"


![Image](https://github.com/zesty-io/website/assets/112954373/1ac435a0-a1c8-4a53-af59-a27ee510b171)
