### ISSUE TITLE
Content Updates: Internal Documentation: document the Docs Parser functionality

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1917]
### Start Date

08/23/2023

### Summary

Update documentation here: https://internal.zesty.io/zesty-apps/zesty-docs-pages

### Basic Example

N/A

### Drawbacks

N/A

**Comment by giseleblair** [comment]
@b-estevez to update the Navigation Section of the document

**Comment by b-estevez** [comment]
Done updating the Navigation Section
