### ISSUE TITLE
Content Updates:🐛 Zesty Docs: H3 has additional margin

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1919]
### Description

H3 elements have margin added to the left making them misaligned
![Screenshot 2023-08-23 at 9 29 26 AM](https://github.com/zesty-io/website/assets/9896546/6bf1a9ea-4138-4244-a381-1331df9fcc6c)

### Reproduction URL

????

### Reproduction steps

```bash
/docs/accounts/settings/instance-settings/
```

**Comment by darwin808** [comment]
e831e289e5a8dc60c81a4c2479982cab6955c576
