### ISSUE TITLE
Content Updates: Error Hydrating in Docs

### ISSUE THREAD

**Issue by tjrabena** [zesty-io/nextjs-website#1939]

**Comment by tjrabena** [comment]
![Image](https://github.com/zesty-io/website/assets/108818160/370e864d-315c-45bc-8434-3413129a52c9)

**Comment by darwin808** [comment]
## JSON Format

**General Format**
`https://yoursite.com/-/instant/zuid.json`

**Content Items**
`https://yoursite.com/-/instant/7-item-zuid.json`

**Models (Previously known as Pagesets, Templatesets, Datasets)**
`https://yoursite.com/-/instant/6-array-zuid.json`


need this format to be remove from manager

**Comment by darwin808** [comment]
@gtllien

**Comment by gtllien** [comment]
@darwin808 There are still few page items displaying **Error hydrating,** you may check google sheet [here](https://docs.google.com/spreadsheets/d/1Z-55V11Mh4xAFr0rvGVFkqTfl9ZdsjYYB8Ni-0vlr0g/edit?pli=1#gid=0)

![image](https://github.com/zesty-io/website/assets/112954373/f245e55d-c111-4dde-a770-4d35d736171f)


Looping in @giseleblair
