### ISSUE TITLE
Content Updates: /docs/accounts/ broken layout

### ISSUE THREAD

**Issue by tjrabena** [zesty-io/nextjs-website#1947]
https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-e092db91a5-rgfcx2/7-84cfca9bf8-vxst0j
https://kfg6bckb-dev.webengine.zesty.io/docs/accounts/?toJSON

**Comment by tjrabena** [comment]
Being investigated by @gtllien and @b-estevez

**Comment by darwin808** [comment]
/docs/tools-and-resources/integrations/marketo-custom-integration/

**Comment by gtllien** [comment]
Fixed on new page path: /docs/tools-and-resources/integrations/marketo-custom/
