### ISSUE TITLE
[MOBILE] homepage

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#195]
Please put image at top above "simplify your work" - only on mobile

![Screenshot_20220321-091526_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159325996-41b3f37a-4eda-44d3-8b53-dc0aab28f765.jpg)

**Comment by giseleblair** [comment]
@Katiemoser  this was resolved. Previously submitted issue: https://github.com/zesty-io/nextjs-website/issues/83
![Screen Shot 2022-03-21 at 6 06 08 PM](https://user-images.githubusercontent.com/9896546/159326606-8b4ff189-200a-4272-9901-f9f4867f1590.png)
