### ISSUE TITLE
🐛 Copy Link button issue

### ISSUE THREAD

**Issue by b-estevez** [zesty-io/nextjs-website#1967]
### Description

Under **API-Reference** content items, the `link icon: 🔗` should copy the full url of the end point:

![image](https://github.com/zesty-io/website/assets/55866499/f930e115-3eb9-4d6c-b424-09b3f82b64c8)

### Reproduction URL

https://kfg6bckb-dev.webengine.zesty.io/docs/accounts/api-reference/instances/#Update-Instance

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by darwin808** [comment]
we have the copy button on right side of the code @b-estevez
