### ISSUE TITLE
🐛 [BUG] - Missing OpenGraph Types Metadata Social Platform 

### ISSUE THREAD

**Issue by jomarmontuya** [zesty-io/nextjs-website#1972]
### Description

Fix OpenGraph Tags 

Test Opengraph here -> https://developers.facebook.com/tools/debug/

### Reproduction URL

zesty.io/mindshare

### Reproduction steps

```bash
1. Go to zesty.io/mindshare
2. Click on article
3. Scroll down copy the url and test it on the opengraph tester
4. See error
```

**Comment by darwin808** [comment]
need to modify the conten json like the one in homepage with this https://kfg6bckb.media.zesty.site/ format
