### ISSUE TITLE
Algolia: Algolia crawler configuration

### ISSUE THREAD

**Issue by tjrabena** [zesty-io/nextjs-website#1975]

**Comment by tjrabena** [comment]
@jomarmontuya and @darwin808 to touchbase

**Comment by jomarmontuya** [comment]
https://github.com/zesty-io/website/tree/feat/doc-search

PR for the docsearch component implemented

**Comment by tjrabena** [comment]
Deployed to dev

**Comment by jomarmontuya** [comment]
Changes deployed to dev -> https://github.com/zesty-io/website/commit/4484b83eb60457c0e2e25dce0872f3605d4c416f
