### ISSUE TITLE
specification for optimizing the website project's routing json

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1978]

**Comment by giseleblair** [comment]
Write a spec that will be used in webengine with the requirements to optimize the load times for the ?toJSON endpoints

**Comment by darwin808** [comment]
## total page size of homepage 

### 471kb
![image](https://github.com/zesty-io/website/assets/71545960/373c5f3c-a8e9-4bb4-8059-9e60c36be28f)


### 97 kb
#### removing all navigation json
![image](https://github.com/zesty-io/website/assets/71545960/1865f777-6bbe-4d56-83a7-9477ea4fd9ce)

### 220 kb
#### removing only the flyout navigation
https://www.zesty.io/-/flyoutnavigation.json
![image](https://github.com/zesty-io/website/assets/71545960/552868d3-99e5-403e-aaca-456a74ed8757)
