### ISSUE TITLE
Algolia: add content to be indexed in crawler

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1979]

**Comment by giseleblair** [comment]
![Image](https://github.com/zesty-io/website/assets/9896546/7db2764d-6131-47b6-acbd-89c4a0621537)



![Image](https://github.com/zesty-io/website/assets/9896546/7749af0a-583d-4cca-9b57-f5211e5ec17e)

**Comment by tjrabena** [comment]
Deployed to dev

**Comment by jomarmontuya** [comment]
Changes deployed to stage -> https://github.com/zesty-io/website/commit/4484b83eb60457c0e2e25dce0872f3605d4c416f
