### ISSUE TITLE
Button Text update: Book Demo to "Free Consultation"

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#1981]
Change all schedule demo text 
![image](https://github.com/zesty-io/website/assets/729972/a7f3bdee-cc8f-4ef4-b396-bab72ee89634)
to 
`Free Consultation`
![image](https://github.com/zesty-io/website/assets/729972/717ecc7e-c40a-438e-97b2-35518f621179)

Change this site wide

**Comment by jomarmontuya** [comment]
closing completed
