### ISSUE TITLE
💡 [Accounts UI] - Need backdoor signup page

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#1996]
### Summary

Accounts needs an interface where a user can sign up without needing to go through our sales funnel. Currently the only option we have is in our legacy accounts interface. This does not allow users to signup with our latest SSO methods.

### Basic Example

https://accounts.zesty.io/signup

### Drawbacks

N/A

**Comment by darwin808** [comment]
@giseleblair we can also signup [here](https://www.zesty.io/join/)
