### ISSUE TITLE
[MOBILE] solutions page - fix header

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#200]
Please fix spacing of header. Zesty is off to the side for some reason and spacing between lines is off.

![Screenshot_20220321-091752_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159327362-c0e68ca1-8dbd-4d01-ba31-566c6b91f9fd.jpg)

**Comment by darwin808** [comment]
![Screenshot_2022-03-22_01-25-35](https://user-images.githubusercontent.com/71545960/159329776-809a10c5-0592-4792-8d62-6e7240ef910c.png)
![Screenshot_2022-03-22_01-25-48](https://user-images.githubusercontent.com/71545960/159329782-ca618e65-7f64-4c51-832c-5fe2d29f5572.png)

**Comment by Katiemoser** [comment]
approved, thank you!
