### ISSUE TITLE
[MOBILE] solutions page - fix padding

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#203]
See below - please add additional padding on each side

![Screenshot_20220321-091927_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159328273-306c06ce-cdfc-4456-84c4-c421377dba25.jpg)

**Comment by darwin808** [comment]
![Screenshot_2022-03-22_01-33-11](https://user-images.githubusercontent.com/71545960/159331000-1f1d2caa-63b5-4432-9e3a-78a6815116c1.png)
![Screenshot_2022-03-22_01-33-17](https://user-images.githubusercontent.com/71545960/159331006-b7258aa8-0da6-4e20-88a0-c8191c297996.png)

**Comment by Katiemoser** [comment]
Approved.
