### ISSUE TITLE
[MOBILE] headless cms - indents

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#204]
Please fix indenting on mobile- see below

![Screenshot_20220321-091959_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159328452-3715fc73-396d-4537-a492-2a1fac2c8de3.jpg)

**Comment by darwin808** [comment]
![Screenshot_2022-03-22_02-58-18](https://user-images.githubusercontent.com/71545960/159344652-a88172cc-c60b-44c1-8c2f-fe7c74160ef7.png)
![Screenshot_2022-03-22_02-58-27](https://user-images.githubusercontent.com/71545960/159344665-3bb56b68-214b-437e-ae3d-96674879a964.png)

**Comment by Katiemoser** [comment]
Approved.
