### ISSUE TITLE
[Accounts - UI] Button for Manage Teams is missing

### ISSUE THREAD

**Issue by b-estevez** [zesty-io/nextjs-website#2041]
### Description

Looking from the old UI, you can modify teams in the accounts ui by clicking the gear icon ⚙️

![image](https://github.com/zesty-io/website/assets/55866499/e6e02cea-3da5-4529-a547-86f04d6a71dd)

However from the new Accounts UI, there is no button for managing the existing teams

![image](https://github.com/zesty-io/website/assets/55866499/f5e70bdc-6048-4fa4-8ed5-899a01765f7f)

This feature is necessary to update the current docs with the new UI: https://zesty.org/services/accounts-ui/teams

### Reproduction URL

https://www.zesty.io/teams/

### Reproduction steps

```bash
N/A
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by glespinosa** [comment]
@b-estevez I did some changes now on this, once the stage merge to prod it will reflect this pr fix.
