### ISSUE TITLE
[MOBILE] developer resources page CTA buttons

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#210]
Top CTA button is not rendering properly on mobile. Can we make this match how the homepage buttons are styled?

![Screenshot_20220321-095640_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159329709-95feecc1-d400-4f7e-9aa3-b0009b16ed4a.jpg)

**Comment by Katiemoser** [comment]
@bltarkany - this is also happening in desktop

**Comment by bltarkany** [comment]
@Katiemoser - The Try Free cta correct?

**Comment by Katiemoser** [comment]
@bltarkany Yes, that's correct. It should look like the other blue CTAs on the site.
