### ISSUE TITLE
[MOBILE] developer resources - bottom form

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#211]
Remove " we'll get back to you in 1-2 days" and "data policy and cookie policy"

![Screenshot_20220321-095657_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159329895-36958595-094a-4785-80d7-0dd35eddc781.jpg)

**Comment by bltarkany** [comment]
@Katiemoser do you want to keep the privacy policy link?

**Comment by Katiemoser** [comment]
Sure, we can keep that. Can you link it to our privacy policy page? Thanks!
