### ISSUE TITLE
[MOBILE] about us - images

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#212]
Can we fix how the images are showing up on mobile? See how the first image just shows the tree/wall of the cubicle? Can we make it so that it shows the people?

![Screenshot_20220321-095714_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159330105-db2b9056-78f9-4d49-84b4-0181bf3c4c1c.jpg)

**Comment by d88naimi** [comment]
@chloespilotro This is a tough one if we want to get the image to show all the content it would like this 
![Screen Shot 2022-03-25 at 8 44 01 AM](https://user-images.githubusercontent.com/22800749/160155391-8c560baa-b60d-4446-88d5-7df70936c58c.png)


My recommendation is stack all the images for mobile view only and would look something like this 
![Screen Shot 2022-03-25 at 8 50 29 AM](https://user-images.githubusercontent.com/22800749/160155469-31872a81-6767-4cc4-b1eb-9c794fd81f87.png)

Dev Notes * 
grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
![Screen Shot 2022-03-25 at 8 53 34 AM](https://user-images.githubusercontent.com/22800749/160155736-323a7bcf-6f3e-4f19-8804-748909cc4320.png)
