### ISSUE TITLE
[MOBILE] zesty explorer on mobile

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#215]
The Zesty explorer button is a bit intrusive on mobile and also overlaps the chat button. Can we make smaller and move to the bottom left corner?

![Screenshot_20220321-091848_Chrome.jpg](https://user-images.githubusercontent.com/101665566/159330701-45907fc4-23b9-4ff9-b39f-57312429e955.jpg)

**Comment by giseleblair** [comment]
@Katiemoser Zesty explorer is only for development purposes, this will not display in production.
