### ISSUE TITLE
website: 🐛 [Bug]: update images  

### ISSUE THREAD

**Issue by darwin808** [zesty-io/nextjs-website#2150]
### Description

https://www.zesty.io/docs/authentication/microsoft-sso/

update the new login page image 

### To Reproduce

```bash
go to https://www.zesty.io/docs/authentication/microsoft-sso/
```

### Current vs. Expected behavior

```bash
outdated login page image
```

### Which area(s) are affected? (Select all that apply)

Docs

**Comment by gtllien** [comment]
Login page Image now updated. 
See screenshot:
![image](https://github.com/zesty-io/website/assets/112954373/2b858a58-a64a-409d-92fd-c21cf170770e)
