### ISSUE TITLE
Logic needed for images

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#220]
ZestyHead.js component will need logic to loop through images and select an image. Please create a issue for this and tag me

More context: https://zesty-io.slack.com/archives/C02HHN7ALTU/p1647884783567889

**Comment by chloespilotro** [comment]
re: all images, also og:image

**Comment by loteoo** [comment]
Hope I don't butt in too much but you guys could use something like [Thumbsmith](https://thumbsmith.com/) to automate these!

(Full disclaimer, I'm the developer behind it 😬)
