### ISSUE TITLE
Website: 🐛 [Bug]: Broken Demo form on PPC landing page

### ISSUE THREAD

**Issue by samsimlai** [zesty-io/nextjs-website#2214]
### Description

Any email shared through the Demo form on the PPC landing page (https://www.zesty.io/ppc/explore/) is currently going nowhere. 
No confirmation message appears when a user adds an email to request the demo.
No email gets sent to any new emails leads requesting a demo. 
The user should be directed to the Demo sign up page in a new tab which isn’t currently happening. (Demo sign up page - https://www.zesty.io/demos/video/ )

<img width="1086" alt="image" src="https://github.com/zesty-io/website/assets/16765661/99c63b37-a585-4a79-b3eb-82698bab9ee7">

**Comment by jomarmontuya** [comment]
PR -> https://github.com/zesty-io/website/pull/2243
