### ISSUE TITLE
Homepage - hero text size

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#224]
Please make eyebrow, title and description text size match that of the "why zesty" page. (DON'T change colors) See comparisons:

![image](https://user-images.githubusercontent.com/101665566/159341273-33fbb179-73b9-4504-8eef-7fb1b41f5640.png)
<img width="953" alt="Screenshot by Snip My at Mar 21, 2022 at 11:37:27 AM" src="https://user-images.githubusercontent.com/101665566/159341381-daed23cd-13c6-4e69-8017-976e4a20dc75.png">

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_03-35-30](https://user-images.githubusercontent.com/71545960/159561529-17ec8de3-8670-4e53-9e40-dba73d2215cd.png)

@Katiemoser this is the updated whyzesty page

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_03-50-07](https://user-images.githubusercontent.com/71545960/159563958-14402c87-461b-4df7-b9e6-818c9811fdae.png)

**Comment by Katiemoser** [comment]
Thank you!
