### ISSUE TITLE
Website: Update CTAs on Demo Page with Even-Length Descriptions

### ISSUE THREAD

**Issue by samsimlai** [zesty-io/nextjs-website#2244]
We need to revise the text descriptions under our CTAs on the demo page to ensure a balanced visual appeal. 
The updated content should be of similar character length (80-90 chars) for each description, to look neater against white spacing.

- Update the description for the "Tailored Demo" section to:
- "Discover how our solutions meet your unique needs. Schedule a personalized demo today."
- Update the description for the "Discovery Call" section to:
- "Let's discuss your content challenges together. Book your discovery call now."
- Update the description for the "Free Trial" section to:
- "Experience the Zesty.io CMS firsthand with a free trial. Fill out the form to start exploring."

Current header - 'How would you like to engage?'
Header alternatives - https://docs.google.com/document/d/11je4wl0P7mGlAxA73D47ueTOaRqD_K9ac0ZN-g34IiM/edit

**Comment by jomarmontuya** [comment]
@SamriddhiSimlai26  -> this is resolved please review
