### ISSUE TITLE
Why Zesty - it's more than a headless solution - fix bullet point styling

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#226]
Can we make the text line up in the middle of each bullet instead of the top?

![image](https://user-images.githubusercontent.com/101665566/159342308-df9a3aec-281c-4f5d-ae3d-97d609bcf486.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-22_13-29-08](https://user-images.githubusercontent.com/71545960/159414128-710effa2-f616-4c06-9967-819f047bb8e7.png)
![Screenshot_2022-03-22_13-29-17](https://user-images.githubusercontent.com/71545960/159414138-0dde1d6d-bd35-4b27-a31e-ffe26ddec44e.png)

**Comment by Katiemoser** [comment]
Approved.
