### ISSUE TITLE
Website: Update G2 badges on Home Page & Demo Page

### ISSUE THREAD

**Issue by samsimlai** [zesty-io/nextjs-website#2279]
@jomarmontuya 
Need to update G2 2023 badges to the new 2024 ones on 2 website pages - 
1. https://www.zesty.io/
2. https://www.zesty.io/demos/

<img width="1374" alt="image" src="https://github.com/zesty-io/website/assets/16765661/6222dd61-19c9-4426-a410-f2ba32c0bd9a">

**Comment by jomarmontuya** [comment]
Awaiting confirmation from Sam, regarding what 2024 badges to use
