### ISSUE TITLE
Homepage - Industry Insights section not pulling correct header text

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#228]
Please update description text to match what is on "why zesty" page industry insights card section ("Stay up-to-date with the latest in digital experience, content management and more.")

Current
![image](https://user-images.githubusercontent.com/101665566/159343926-eaaa10b3-37ba-4213-8e55-b647fa8389b0.png)

**Comment by d88naimi** [comment]
This one is hardcoded I updated and will be out on the next deploy
