### ISSUE TITLE
Website: Feature: Small Popup Modal for Downloading Gated Content on 'Mindshare' Articles

### ISSUE THREAD

**Issue by samsimlai** [zesty-io/nextjs-website#2287]
@jomarmontuya  Create a gated content popup modal that appears on 'Mindshare' blog article pages, offering users the opportunity to download gated content (default: CMS Buying Guide) through any article in exchange for their work email and name. 

This lets marketing experiment with top performing content pages to generate MQLs. Our organic traffic is being generated largely from our Mindshare pages.

**Popup Modal Activation:**
- Trigger: Appears by default only on 'Mindshare' blog article pages.
- Dismissal: If dismissed, the popup should not reappear for the user on the same article for 15 days.

**Content Download Process:**
- The default downloadable content for all articles: CMS Buying Guide.
- User Requirement to download: Enter a valid work/lead email, first name and last name (with work email validation).
- Post-Download Message: "Thank you for downloading our guide. Reach out to us for a free discovery call, demo call or a free trial." (Links to the Demo page)
- Dismissal: 
- Once the thank you note pops up, there should be a close button to dismiss the popup after download. . Once a user clicks the dismiss button, the pop up is dismissed for that user for the next 15 days. 
- However a separate pop up modal on a different article with a different CTA should still show up. For eg. A user reads an XYZ article which has a pop-up to download our buying guide. User dismisses pop-up. User navigates to a new article which has a different 'Download Ebook' CTA. Users should be shown the ‘Download Ebook’ pop-up.

**Customization Capability:**
- Gated Content File and Pop- Up title can differ in different article pages.
- Should be customizable by a marketer. Marketers should be able to turn the pop-up modal on or off for an article page. The default should be on.
- Customizable Elements: Gated Content File (PDF file/spreadsheet), Popup Title
- Default Popup Title: "Download Free CMS Buying and ROI Guide."
- Default File: CMS Buying Guide

**User Engagement:**
- Even if the user does not engage with the download CTA, a dismiss (close) button should be present. 
- Upon user’s dismissal without engagement, the popup should not show for that session or for the next 24 hours.
- If a user encounters a different article with a different CTA, the new popup should still be displayed.
- If a user doesn’t dismiss the pop-up with the Close button, it should stay through the user’s session.

**Previous Art**
https://vwo.com/blog/increase-website-conversion-rate/
<img width="607" alt="image" src="https://github.com/zesty-io/website/assets/16765661/8d483478-9556-4a23-adb5-aeee8a4c2208">

**Comment by jomarmontuya** [comment]
Continue working on this issue today

**Comment by jomarmontuya** [comment]
Completed this task, will meet sam today to show and review it together

**Comment by jomarmontuya** [comment]
Sam: requested to make the content dynamic and the pdf per article, but set the cMS buying guide as default

**Comment by jomarmontuya** [comment]
Related PR -> https://github.com/zesty-io/website/pull/2311
