### ISSUE TITLE
Pricing Page - CTA buttons

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#232]
CTA buttons are not matching what's in the content manager (ex: enterprise button should say "contact sales" or "contact us" and link to a contact form instead of saying "start now".

![image](https://user-images.githubusercontent.com/101665566/159374986-49f1ce9e-3f6c-4ab0-a655-083d54c9993a.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-24_01-19-23](https://user-images.githubusercontent.com/71545960/159758322-ea34312f-ac55-4b22-baf5-d4ba31c06059.png)

@Katiemoser  @chloespilotro the cta button has no internal links

**Comment by darwin808** [comment]
![Screenshot_2022-03-24_01-24-03](https://user-images.githubusercontent.com/71545960/159759185-6d14f360-fe3b-4697-b851-9dfd0e269548.png)
![Screenshot_2022-03-24_01-24-12](https://user-images.githubusercontent.com/71545960/159759189-88ac2657-1a39-41fa-bffc-54decd9e747e.png)

only 1 button  has  a value

**Comment by chloespilotro** [comment]
They now have value, but they are all triggering the same modal

**Comment by chloespilotro** [comment]
Confirmed this looks good now @darwin808 except the Enterprise tier has a custom button we want to use to send people to the demos page, can you please update that? Button is hooked up in CMS.

**Comment by darwin808** [comment]
![Screenshot_2022-03-24_01-32-07](https://user-images.githubusercontent.com/71545960/159760712-7ca2e167-92d7-46d8-a1d2-291ac1103102.png)
![Screenshot_2022-03-24_01-32-15](https://user-images.githubusercontent.com/71545960/159760719-00305d96-b2e4-452e-bddd-3882d21b2107.png)

**Comment by darwin808** [comment]
@chloespilotro Enterprise button same button but when user click user will redirect to /demos?

**Comment by chloespilotro** [comment]
enterprise button has info in the CTA 
Button text and link should pull from cms

**Comment by darwin808** [comment]
![Screenshot_2022-03-24_01-40-21](https://user-images.githubusercontent.com/71545960/159762255-c4d4e036-b54a-4a24-9bd8-197062c5dd2d.png)
it doesnt have link
