### ISSUE TITLE
🐛 [Bug]: 404 Error on Article URL Accessed via Organic Search Result

### ISSUE THREAD

**Issue by samsimlai** [zesty-io/nextjs-website#2327]
### Description

@arzljames Recording a redirect issue with a Mindshare article URL. While this URL opens as expected when accessed directly from our marketing website, the same URL results in a 404 error when clicked from search engine results.
URL: https://www.zesty.io/mindshare/zesty-io-the-best-cms-for-seo/
Check error recording:
https://drive.google.com/file/d/18P4GUbiri8DR3YVS3BxtorR6qVlQvei4/view?usp=sharing

Error screenshots:
<img width="1108" alt="image" src="https://github.com/zesty-io/website/assets/16765661/0ee744d3-92db-40cf-aba7-0e683f2c5db6">
<img width="1047" alt="image" src="https://github.com/zesty-io/website/assets/16765661/90bfd2ed-d56a-4b44-bcf7-1295048a4913">

### Current vs. Expected behavior

The article URL should open the correct content regardless of the source of access, whether it is direct navigation from the marketing site or from organic search results.

**Comment by arzljames** [comment]
Fixed by adding a redirect 301 


![Image](https://github.com/zesty-io/website/assets/70579069/8b590d66-5caf-4403-825f-0efff005d0f9)
