### ISSUE TITLE
🐛 [Bug]: 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/nextjs-website#2339]
### Description

1. Could you look into why this related article is not appearing in the related articles product articles section here https://www.zesty.io/mindshare/the-improved-wysiwyg-editor-experience-is-here/?
2. Zesty Content Item: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-45a908-qfw88c/7-9097c3f1fa-xcsqwk
3. Could you also ensure that in the related articles section we do not show the current article?

![CleanShot 2024-01-26 at 04 54 32](https://github.com/zesty-io/website/assets/22625919/383a457b-2ab4-4dea-8382-95789ffabfb5)

![CleanShot 2024-01-26 at 04 55 47](https://github.com/zesty-io/website/assets/22625919/358b6faa-3ed2-4ece-9ba1-d634a54a7e7d)

**Comment by arzljames** [comment]
Taking a look at this @zcolah

**Comment by arzljames** [comment]
Continue working for the fix. Testing on my local end and will push PR later today

**Comment by arzljames** [comment]
PR created -> https://github.com/zesty-io/website/pull/2340
