### ISSUE TITLE
About Us - add two more rows of headshots

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#234]
Please add two more rows of headshots beneath the ones currently there.

![image](https://user-images.githubusercontent.com/101665566/159377747-37d5a223-1283-4ce0-b9b8-a5f42ee1fdb8.png)

**Comment by bltarkany** [comment]
@Katiemoser it will continue to allow you to add as many team members you want. The blocker comes in for the one-to-many field it has a character limit that will need to be increased by the backend. I'll have them increase it and you can add as many more as you would like

**Comment by Katiemoser** [comment]
Ohhh okay got it. Yeah I tried to add three more people and it wouldn't save. They were on the page previously though. Lmk what I need to do on my end.

**Comment by Katiemoser** [comment]
Ohhh okay got it. Yeah I tried to add three more people and it wouldn't save. They were on the page previously though. Lmk what I need to do on my end.

**Comment by Katiemoser** [comment]
Thanks Bobbi!
