### ISSUE TITLE
Implement Unique ID for "Download Now" Button in Mindshare Modal for Accurate Conversion Tracking

### ISSUE THREAD

**Issue by samsimlai** [zesty-io/nextjs-website#2344]
### Description

- @arzWe have set up conversion tracking for LinkedIn Ads for the Mindshare pop-up Modal with ‘Download Now’ CTA. However, currently, conversion tracking in LinkedIn and any other advertising platform is based on the name/text of the "Download Now" button. 
- This approach may lead to inaccuracies in tracking gated content downloads due to possible variations in button naming conventions or if multiple buttons have the same name. 
- For better accuracy of our conversion tracking, we need to update our codebase to assign a unique ID to the "Download Now" button for gated content.

### To Reproduce

```bash
Assign a Unique ID to the "Download Now" Button
Update Conversion Tracking Implementation
Test accuracy of Download conversions with Marketing team
```

**Comment by arzljames** [comment]
**Updated trigger configuration in google tag manager:**
![Image](https://github.com/zesty-io/website/assets/70579069/f68d298e-e7bb-4b6c-a7bb-468cbaf8a72b)

**Added a unique ID to the button of popup modal:**
![Image](https://github.com/zesty-io/website/assets/70579069/48874c82-ecd2-4cdd-b245-70a1522e6405)

This is to improve accuracy in conversion tracking.
