### ISSUE TITLE
🚀 [Feature]: Account-ui Instance Search Enhancement

### ISSUE THREAD

**Issue by jomarmontuya** [zesty-io/nextjs-website#2347]
### Feature Description

```bash
Instance search inside account-ui should support, searching by Legacy ID

e.g.8356550
```

**Comment by jomarmontuya** [comment]
@shrunyan 

I've just looked into this now and it looks like its has support for searching this legacy ID/ or ID. 



![Image](https://github.com/zesty-io/website/assets/61284357/7ba710f9-9ec2-4279-8d72-901272e4cf9c)

here's one for example

![Image](https://github.com/zesty-io/website/assets/61284357/84d56b03-40f7-4a7f-a6ab-26cd9caa7faf)



![Image](https://github.com/zesty-io/website/assets/61284357/924bcffd-d7a8-44bd-b899-f0b1e4ebcc93)

But this petdesk demo is not specifically legacy instance. But I'm assuming as long as you have support for this ID it should be good right? or am i wrong here?

**Comment by shrunyan** [comment]
![image](https://github.com/zesty-io/website/assets/208819/277ec95e-80a5-4f36-9263-396c73c516bd)

it seems to be the top right search which is not allowing for legacy ids
