### ISSUE TITLE
Solutions Page - Case studies CTA button

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#236]
Button is not pulling the correct info. It should read "see what you can do" per the content manager selection "CTA" at the bottom of the schema for this page.

![image](https://user-images.githubusercontent.com/101665566/159520159-4e88bff2-b274-48cd-a270-ce19187843a6.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_01-43-33](https://user-images.githubusercontent.com/71545960/159542853-2eafad8d-76d8-469d-800b-7b5ec26dd221.png)

**Comment by Katiemoser** [comment]
Approved!
