### ISSUE TITLE
🐛 [Bug]: Broken Pricing Page

### ISSUE THREAD

**Issue by jomarmontuya** [zesty-io/nextjs-website#2368]
### Description

Pricing page is broken
![image](https://github.com/zesty-io/website/assets/61284357/c866d5b1-1f22-405a-aac0-d4e0ffef0f09)

This one might be a bit urgent as we are driving traffic to this page.

CC: @giseleblair 

### To Reproduce

```bash
1. Visit -> https://www.zesty.io/pricing/
```

**Comment by jomarmontuya** [comment]
![Screenshot 2024-02-20 at 7 43 49 AM](https://github.com/zesty-io/website/assets/61284357/814a8262-4646-45fa-baea-83c495d51aba)


@giseleblair  Looks like the one-to-many relationship returning a string of item_zuid for some reason.  This should have been an array and I figure this breaking the pricing page.

**Comment by giseleblair** [comment]
@jomarmontuya can you share the link to the zesty item that has the one-to-many field

**Comment by giseleblair** [comment]
Also, your screenshot doesn't look like what's in prod, can you confirm

**Comment by jomarmontuya** [comment]
@giseleblair  I'm closing this as resolve, this is the same issue last night for webengine returning one-many data's as string
