### ISSUE TITLE
Solutions & Headless CMS pages - features boxes title font size

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#237]
Font size too large on this component's titles. Please drop to match screenshot below.

Current
![image](https://user-images.githubusercontent.com/101665566/159520800-a46d6ce4-bfd6-44ed-acd4-86bbdc9568de.png)

Change font size on title to match titles here (this is on the Headless CMS page):
![image](https://user-images.githubusercontent.com/101665566/159520984-1a70fb78-3022-4555-ae48-38e1060359f0.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_00-51-04](https://user-images.githubusercontent.com/71545960/159532894-b6817e01-4bba-42fa-9228-4db34cc8644c.png)
![Screenshot_2022-03-23_00-51-18](https://user-images.githubusercontent.com/71545960/159532901-eaea2c94-5165-454d-a9c9-8f1e216a25c6.png)

**Comment by Katiemoser** [comment]
Approved, thank you!
