### ISSUE TITLE
Solutions & Why Zesty pages - orange bullet points spacing

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#238]
For both Solutions and Why Zesty pages: Spacing between bullet points is too large. Please bring back to original spacing.

![image](https://user-images.githubusercontent.com/101665566/159521195-d82c8236-9d86-4cbe-af41-223069a1df98.png)

![image](https://user-images.githubusercontent.com/101665566/159521317-c0e9e360-d412-4a54-9cbd-77f8bf71be8b.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_00-42-07](https://user-images.githubusercontent.com/71545960/159531286-4b2fa661-a20c-4427-a483-70fa38babdbd.png)
![Screenshot_2022-03-23_00-42-28](https://user-images.githubusercontent.com/71545960/159531298-9a528577-5ccd-4cd0-bb2d-51c0e4989318.png)
![Screenshot_2022-03-23_00-42-44](https://user-images.githubusercontent.com/71545960/159531300-3ddd0153-a157-4775-9fca-82ddb5cbd684.png)
![Screenshot_2022-03-23_00-43-01](https://user-images.githubusercontent.com/71545960/159531308-5d49de82-3670-4661-937a-66d56cfff5f0.png)
