### ISSUE TITLE
Update homepage logos

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#243]
https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-0888e8-0rv8xh/7-c28c9fc9b1-st2xwm

Programmatically changing logo colors using the APIs is not consistent, can we please change so that light mode pulls `grey-logo` and dark mode pulls `white-logo`, new fields we just added. Ty!

**Comment by chloespilotro** [comment]
CC @Katiemoser for visibility

**Comment by giseleblair** [comment]
@Katiemoser @chloespilotro can we get content in those fields so we can test

**Comment by Katiemoser** [comment]
Yes, working on it now. The grey & full color are in, the white should be in soon.

**Comment by Katiemoser** [comment]
@chloespilotro  - can you address this?
