### ISSUE TITLE
Dark mode - hero images not rendering on Solutions page

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#250]
![image](https://user-images.githubusercontent.com/22846981/159573518-a38aad86-d03a-4e80-a512-bfca0f2bb7b5.png)
Please resolve to match light mode- same images is fine.

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_13-43-25](https://user-images.githubusercontent.com/71545960/159632108-f6c97e94-d67c-46bb-8fa1-74ee6c9f6e72.png)
![Screenshot_2022-03-23_13-43-31](https://user-images.githubusercontent.com/71545960/159632114-e0b4b28b-6de5-437c-869c-d98b43528746.png)
