### ISSUE TITLE
Dark mode - please fix header fonts to be light

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#251]
Seeing this on solutions page, please make header and body font match the styling below it as this is currently hard to read. 

![image](https://user-images.githubusercontent.com/22846981/159573727-24605a60-996b-4be9-86d4-1750134c824a.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_13-59-46](https://user-images.githubusercontent.com/71545960/159633809-8fcb7a33-7c06-44d2-bb4b-99360d8b7fde.png)
![Screenshot_2022-03-23_14-00-14](https://user-images.githubusercontent.com/71545960/159633820-7d994735-178a-4f4e-addc-6fd77d1e8e50.png)
