### ISSUE TITLE
Dark mode - please fix eyebrows to be white

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#252]
![Screen Shot 2022-03-22 at 1 54 05 PM](https://user-images.githubusercontent.com/22846981/159574174-7a6807b9-c7e7-46f2-8829-c5fe90428adf.png)

**Comment by chloespilotro** [comment]
on /solutions/ page

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_13-43-25](https://user-images.githubusercontent.com/71545960/159631834-1c067b5d-1ae3-41c2-a338-2d542bee7104.png)
![Screenshot_2022-03-23_13-43-31](https://user-images.githubusercontent.com/71545960/159631840-4047b663-ebb9-4a64-97f1-8e07cd50f853.png)
