### ISSUE TITLE
Dark mode - clients page, need to fix logos on tiles

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#255]
Some are funky? maybe we just use the white logos instead in dark mode. Thoughts? 

![image](https://user-images.githubusercontent.com/22846981/159575388-86378fff-104f-4a54-8be1-232780faaeb3.png)

**Comment by chloespilotro** [comment]
Wrong image - 

![image](https://user-images.githubusercontent.com/22846981/159575483-10f4c90c-9007-48f6-9078-6353e2c6058a.png)

**Comment by Katiemoser** [comment]
Fixed the ones showing up as squares. Will still want white logos for these. LMK how we want to proceed. @chloespilotro
