### ISSUE TITLE
Dark mode - please fix checkmarks on headless CMS page

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#256]
![image](https://user-images.githubusercontent.com/22846981/159576535-ba4afa99-67fa-4aa4-a555-3d0a2636deb9.png)

Let's make these blue in dark mode to match the other pages. Thank you!

**Comment by darwin808** [comment]
![Screenshot_2022-03-23_13-37-41](https://user-images.githubusercontent.com/71545960/159631152-d56b1aa0-7db8-44b7-9ac5-63739bee7271.png)
