### ISSUE TITLE
About page - missing stats

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#259]
![image](https://user-images.githubusercontent.com/22846981/159577335-8ddf7c2d-1c69-4fa0-86d0-30d8f41394b9.png)
just needs content

**Comment by giseleblair** [comment]
@chloespilotro @Katiemoser please pass along the field or content model that needs to be referenced in the stats component

**Comment by Katiemoser** [comment]
It's already set up, I just am waiting for that last bit of content. Will address today.
