### ISSUE TITLE
Dark mode - about page, logos not loading

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#260]
Can you help us troubleshoot this? 

![image](https://user-images.githubusercontent.com/22846981/159577495-91164eb9-c7a4-42f1-abb4-75b5724ccf33.png)

**Comment by bltarkany** [comment]
@chloespilotro do we have transparent background images for these logos? The white background does not look great in dark mode
![image](https://user-images.githubusercontent.com/50595614/159714433-64077965-a583-4c2f-976f-c36126c26915.png)

**Comment by chloespilotro** [comment]
Working on solution
