### ISSUE TITLE
/meet/ please remove erroneous content

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#262]
"Missing content" please remove this item 
![image](https://user-images.githubusercontent.com/22846981/159578369-c3c69623-586a-4a39-906c-0599b45d422d.png)

**Comment by bltarkany** [comment]
so you no longer want the eyebrow on this page buildout?

**Comment by chloespilotro** [comment]
@Katiemoser to put in content for this page, will close when that is completed

**Comment by Katiemoser** [comment]
Content complete, @bltarkany removing eyebrow. Please close when complete.
