### ISSUE TITLE
Dark mode - meet, testimonial slider logos not loading properly

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#263]
![image](https://user-images.githubusercontent.com/22846981/159578486-fe5c0dbf-448d-4ff4-b234-c793d6b13cb2.png)

Can you please help us fix?

**Comment by chloespilotro** [comment]
there's a few items that say "missing content," please remove each one. Thank you!

**Comment by chloespilotro** [comment]
wrong image for this issue - 

![image](https://user-images.githubusercontent.com/22846981/159578623-d8562728-2ce3-43e7-977e-ea64dbe9d4a2.png)

**Comment by bltarkany** [comment]
@chloespilotro we are going to run into another background issue here, the images don't have a transparent background. Would you like to use their white logos in dark mode?

**Comment by chloespilotro** [comment]
Working on solution now.

**Comment by Katiemoser** [comment]
@bltarkany - white logos are added to client cards, please close when synced.
