### ISSUE TITLE
Agency Partners Page - logos getting squished

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#264]
Not sure what's happening here with the Sony and Wattpad logos... can we fix?

![image](https://user-images.githubusercontent.com/101665566/159586058-9754e627-953b-4ba2-a608-e79fedde1251.png)

**Comment by d88naimi** [comment]
@Katiemoser this one I think may need a higher quality image as the rest are looking okay

**Comment by Katiemoser** [comment]
They should all be the same size, I created them all together and uploaded them

**Comment by d88naimi** [comment]
https://zesty-website-m3rbwjxm5q-uc.a.run.app/agency-partners/

Agency logo is using a very small png of 48px can we upload the same image thats from homepage? 

/agency-partners/

<img width="299" alt="Screen Shot 2022-03-22 at 7 14 44 PM" src="https://user-images.githubusercontent.com/22800749/159610413-2aad85ad-2742-4044-ac09-9546c3d32677.png">

homepage
<img width="332" alt="Screen Shot 2022-03-22 at 7 14 16 PM" src="https://user-images.githubusercontent.com/22800749/159610362-85c48c57-5998-4847-be17-bb382c05bdaa.png">

**Comment by Katiemoser** [comment]
Odd... I made and uploaded them all together so I'll look in the manager.

**Comment by chloespilotro** [comment]
Theyre now all the same size but pushing the 5th to a new row @d88naimi. Marking as Phase II
