### ISSUE TITLE
CTA Button - Why Zesty Rocket League Case Study

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#279]
button is taking me to the live Zesty homepage instead of to the designated internal link in the client card.

![image](https://user-images.githubusercontent.com/101665566/159780666-3b79aa7c-c983-4fe8-80bc-fae91c36d01d.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-24_03-33-38](https://user-images.githubusercontent.com/71545960/159781326-58264acc-4842-4af9-a81c-108216d9ccf0.png)
@Katiemoser the link is empty string

**Comment by darwin808** [comment]
https://kfg6bckb-dev.webengine.zesty.io/why-zesty/ 

@Katiemoser

**Comment by Katiemoser** [comment]
Approved!
