### ISSUE TITLE
CTA Buttons - Solutions Page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#280]
https://kfg6bckb-dev.webengine.zesty.io/solutions/
"Try Zesty free" button in header is not triggering the drop down. Goes to /meet/ page instead

Can we change the "see what you can do" CTA button under the case studies to trigger the drop down that comes up when you click "try Zesty free"?

**Comment by darwin808** [comment]
![Screenshot_2022-03-24_14-53-12](https://user-images.githubusercontent.com/71545960/159859321-4a7418a5-141e-4dd4-97b4-7939b9bbc3bb.png)
![Screenshot_2022-03-24_14-53-23](https://user-images.githubusercontent.com/71545960/159859330-7e02d765-b232-4c4c-8f45-58008584c135.png)
