### ISSUE TITLE
Authors page sort

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#284]
Can we fix the way the authors are being pulled into this page? I don't see a sort order on the items nor a page to edit. Unsure who was working on this so tagging a few people.

https://kfg6bckb-dev.webengine.zesty.io/mindshare/authors/

**Comment by bltarkany** [comment]
@Katiemoser specifically the order the authors are listed on here??:
[https://kfg6bckb-dev.webengine.zesty.io/mindshare/authors/](https://kfg6bckb-dev.webengine.zesty.io/mindshare/authors/)
![image](https://user-images.githubusercontent.com/50595614/159808331-27d9a270-668f-446d-8504-2a41c2a8ebee.png)

**Comment by Katiemoser** [comment]
Correct.

**Comment by d88naimi** [comment]
@Katiemoser https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-76ccb8-d3dq4j
you can now goto each author and assign a sort order.
![Screen Shot 2022-03-23 at 5 07 40 PM](https://user-images.githubusercontent.com/22800749/159816500-3f5c2283-0119-4338-86ca-5aeb110fe160.png)
