### ISSUE TITLE
Form issues on demo page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#310]
https://kfg6bckb-dev.webengine.zesty.io/demos/
Need to fix:

- "Email" and "website" fields are copying the same text
- Remove "be careful" text at bottom
- Sync image that is in manager with the page
- Make sure form submits to CRM
- Change button color to Zesty orange
- Make sure there is a "thank you for submitting" pop up after someone clicks submit

**Comment by chloespilotro** [comment]
First Name
Last Name
Email
Company: 
Who are we demoing to: Please send this data to the field "Persona Role"

**HIDDEN FIELDS**
Lead Source: Website
Lead Source Detail: Demo Sign Up
Business Type: Direct
Contact Status: Not Contacted
