### ISSUE TITLE
Disappearing SONY logo on dark mode

### ISSUE THREAD

**Issue by dominictarantino** [zesty-io/nextjs-website#329]
On the partners page, the SONY logo disappears in dark mode: 
![image](https://user-images.githubusercontent.com/76065657/160475105-dab07819-df24-4cbd-9a86-47cb3a6ff49a.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/161983081-105d46b2-2356-4eda-ab67-5cd64291c605.png)
