### ISSUE TITLE
Why zesty > proof section no data

### ISSUE THREAD

**Issue by darwin808** [zesty-io/nextjs-website#342]
![Screenshot_2022-03-29_04-51-37](https://user-images.githubusercontent.com/71545960/160485092-f64a011e-deb4-4e15-a2d8-1a0a498a5177.png)

**Comment by Katiemoser** [comment]
@darwin808  - this is supposed to be pulling from "Proof Points" in manager. It is built out in the content manager

**Comment by Katiemoser** [comment]
@giseleblair - I think we need to push "proof points" live.
