### ISSUE TITLE
PPC Campaign Landing Page Template Build

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#350]
I need two templates built to create landing pages for our PPC campaigns (Long form and short form pages). I've built out the schema and content already in the manager, just need the designed template built out. Here is the link to the doc that outlines which content blocks I need from our template and notes about certain elements to take out (for example, some CTA buttons will need to be removed). Please assemble these and connect to the schema.

https://docs.google.com/document/d/1jLt6mOVrSrZk8aE7jNR3LPtW4UnyyRFGYt39QwQ6Ttg/edit?usp=sharing

**Comment by darwin808** [comment]
![2](https://user-images.githubusercontent.com/71545960/160637750-906e5d54-fdba-4fb9-8991-c3da20b5e7c4.png)
header - is it possible to make the header Html

**Comment by Katiemoser** [comment]
I believe it is in the schema - just a text field called "Who is Zesty H2"

**Comment by darwin808** [comment]
![1](https://user-images.githubusercontent.com/71545960/160651986-52cb5714-346f-4926-8003-d89f91bcdd09.png)
![2](https://user-images.githubusercontent.com/71545960/160651993-8db7f198-8133-4acb-b4e2-485df5bded59.png)
![3](https://user-images.githubusercontent.com/71545960/160652000-9072ab86-0f03-4057-9b99-36f66e3d61e5.png)
![4](https://user-images.githubusercontent.com/71545960/160652004-a7b1a37f-3497-433d-b938-e5fcb4033161.png)
![5](https://user-images.githubusercontent.com/71545960/160652007-b6b42af0-dc11-4e3a-8895-8b194c1b1397.png)
![6](https://user-images.githubusercontent.com/71545960/160652010-947659a7-bd52-431d-b382-72ef453f390a.png)
![7](https://user-images.githubusercontent.com/71545960/160652015-1d44c78e-82e2-4ec5-b980-4d6f77eb486c.png)

**Comment by Katiemoser** [comment]
Here are the edits for the long-form page. Let me know if you have any questions:
![Landing Page Edits-long form](https://user-images.githubusercontent.com/101665566/160666335-b6e36be3-d7ca-4ff8-9d7f-01623ab498eb.png)

**Comment by darwin808** [comment]
![1](https://user-images.githubusercontent.com/71545960/160683915-066b9cdd-e15f-46ba-8d8d-1f5207864b31.png)
![2](https://user-images.githubusercontent.com/71545960/160683924-58f3e82c-1146-4bc8-90b4-a215bc572cd9.png)
![3,4](https://user-images.githubusercontent.com/71545960/160683928-a698925e-5421-4ee6-97b7-2cac6087c02c.png)
![5](https://user-images.githubusercontent.com/71545960/160683933-712d5bb6-2c1c-4343-ab2f-cbae24dbd288.png)
![6](https://user-images.githubusercontent.com/71545960/160683939-c62eb15e-d837-4131-9e83-8fd458744d6a.png)
![7](https://user-images.githubusercontent.com/71545960/160683942-8fe88b81-a885-45ae-85c9-36c49e433eed.png)

**Comment by darwin808** [comment]
Hi @Katiemoser  can you draw , im thinking of the form will have white rectangle below and the form has border?

**Comment by Katiemoser** [comment]
I want the whole form to be white like the screenshot above, just the background behind it to be blue.

**Comment by darwin808** [comment]
![Screenshot_2022-03-30_03-04-18](https://user-images.githubusercontent.com/71545960/160686961-b85bae79-8b8f-4fc3-8022-890254f31c7a.png)

**Comment by Katiemoser** [comment]
Sorry, don't need the copy, just the form with the title and description that was there before.

**Comment by Katiemoser** [comment]
I just like the styling of the white on blue.

**Comment by darwin808** [comment]
![wwww](https://user-images.githubusercontent.com/71545960/160691208-bda7f02f-c4d5-4db1-bb81-10758904f57a.png)

**Comment by Katiemoser** [comment]
Is this for the short form page? (/create-engaging-digital-experience-at-scale) If so, keep as is. I want to address the form on the long-form page (/digital-experience-platform)

**Comment by Katiemoser** [comment]
Sorry, I should've separate these. For the long page, I want the form to be white with a background behind it of dark blue, similar to how it's style on the short form page.


**SHORT FORM**
> ![qqq](https://user-images.githubusercontent.com/71545960/160690563-eff5faf8-e4a6-4a69-bcd3-54b8f75aa11e.png) i revert it back the image , the form mostly covered the background image , we should remove the additional input fields?

The short form page is approved above. For logos, can we add a row below the bullet points? Also how should I update the background image? Should I add that into the schema?

**Comment by darwin808** [comment]
![gggg](https://user-images.githubusercontent.com/71545960/160695931-93f4813b-757e-4a0d-acb5-f2572a41abe0.png)

**Comment by Katiemoser** [comment]
Approved
> ![ttttt](https://user-images.githubusercontent.com/71545960/160693354-99d5f63d-bf57-4561-be8a-ccfc677ca023.png)
> 
> shortpage image -yes just put a field for image

**Comment by Katiemoser** [comment]
Let's just do 3 logos.

> ![gggg](https://user-images.githubusercontent.com/71545960/160695931-93f4813b-757e-4a0d-acb5-f2572a41abe0.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-30_15-41-43](https://user-images.githubusercontent.com/71545960/160778228-2a0aa448-298b-4c70-8843-34030ad03ae5.png)
i remove the last 2 logo
