### ISSUE TITLE
Open global nav disables scrolling

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/nextjs-website#354]
![image](https://user-images.githubusercontent.com/208819/160509238-03e55100-1f1e-4647-8289-7670a60c389c.png)

Kind of strange. When a global nav dropdown is open it disables the page scroll bar preventing scrolling. Visually noticeable as the scrollbar is not rendered.

**Comment by d88naimi** [comment]
@shrunyan If you are navigating the header why would the user need to scroll ? This looks to be intentional functionality. @ardeay should I bring scrolling back? TY
