### ISSUE TITLE
About page additions

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#374]
Can we please add an additional section below the headshots that includes:

Title
Description
Headshots (same layout as team headshots)
Space for logos

This is going to be used to display our investors/board. We can use the same layout as the team headshots but add a row for logos.

**Comment by bltarkany** [comment]
@Katiemoser will the logos be next to the board member that works there or will the logos land below all board members

**Comment by Katiemoser** [comment]
Let's have a line of logos below the headshots, not with them. Thank you!

**Comment by bltarkany** [comment]
@Katiemoser I have added the fields for the board member section, title, description, color and dark mode board member logos. Below are a couple of test photos. let me know what you think
![image](https://user-images.githubusercontent.com/50595614/161277391-c1a03f7f-63d5-453b-97ed-40760383506d.png)
![image](https://user-images.githubusercontent.com/50595614/161277416-ada48ca5-b5fc-4738-be16-51bf8eebe504.png)

**Comment by Katiemoser** [comment]
Looks good. Do you think there's a way we can make two headshots across so they're more balanced? Unsure if that would break anything. LMK!

**Comment by bltarkany** [comment]
can do, I have added the fields into the About schema so you can go in and add the content you are looking for.

**Comment by bltarkany** [comment]
@Katiemoser I have updated the format to output in two columns. Let me know if this works for you. If so go ahead and update the content in the manager. I am seeing to different sets of logos for light and dark mode. I can submit my PR after your approval

![image](https://user-images.githubusercontent.com/50595614/161773725-480e7ac8-14cb-4c4b-98fc-3f44f9066c75.png)
![image](https://user-images.githubusercontent.com/50595614/161773768-93410433-6201-497e-971c-2dc32ea946cc.png)

**Comment by Katiemoser** [comment]
Thanks Bobbi! Looks great. On the logos, they look a little squished in the light mode (these are the correct logos that are supposed to be there). Can we fix that and also space them out a bit?

**Comment by bltarkany** [comment]
@Katiemoser adjusted the width to give the logos more space and added spacing between, let me know what you think. Do we have white logos for these or will I need to use the color for both light and dark mode?
![image](https://user-images.githubusercontent.com/50595614/161786503-c285b298-94b2-471d-a41b-7f547174ff15.png)

**Comment by Katiemoser** [comment]
the Band one is still looking stretched for some reason. See how it's supposed to look below:
![Band_of_Angels_(investors)_logo](https://user-images.githubusercontent.com/101665566/161792421-2ef1de49-eafb-43c0-9072-aeeef881a661.png)

**Comment by bltarkany** [comment]
@Katiemoser the white logos came out perfect! But the colored logos for Band and Cove not so much.
![image](https://user-images.githubusercontent.com/50595614/162542872-fae84a8e-78d0-459a-a31b-c1521b38df13.png)
![image](https://user-images.githubusercontent.com/50595614/162542916-2970acf5-1d87-4681-a8d5-e8ec73de0c4e.png)

**Comment by Katiemoser** [comment]
Maybe because the square one isn't in the 200×110 sizing?

**Comment by bltarkany** [comment]
can we test it with the square one as the same size as the others?

**Comment by Katiemoser** [comment]
Square logo has been updated to same size as the others. Sorry this took so long!

**Comment by bltarkany** [comment]
Perfect, I'll send this PR through today

**Comment by Katiemoser** [comment]
@bltarkany - wanted to follow up here and see where we're at with these updates :)
