### ISSUE TITLE
Edits to short form landing page on mobile

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#390]
![Screenshot_20220331-134725_Chrome](https://user-images.githubusercontent.com/101665566/161146984-a3499442-be29-4afd-91bd-96808f1d1e95.jpg)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/161304136-ab272ad2-e708-4b4d-b1bc-4360abc72ec0.png)
![image](https://user-images.githubusercontent.com/71545960/161304407-64c0c68b-bb6a-4c7f-b327-4e3f372c075d.png)

![image](https://user-images.githubusercontent.com/71545960/161304304-d564463c-14ab-471e-b31f-1600712dd94f.png)

**Comment by Katiemoser** [comment]
Let's keep the form below the text

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/161315675-e55e5f09-d6b8-4614-ac8c-4cd5dc4b5575.png)
![image](https://user-images.githubusercontent.com/71545960/161315705-e17ff123-35e5-4f21-9524-03f2b3589896.png)

**Comment by Katiemoser** [comment]
Approved!
