### ISSUE TITLE
PPC Long Form Landing Page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#402]
This section doesn't look like it's pulling the latest info from the headless set "PPC - Zesty Key Attributes" - can we update?

(The last sentence should read: "with a smarter solution that integrates seamlessly with your tech stack to keep business objectives moving" so I want to make sure these are connected if I make any changes)

![image](https://user-images.githubusercontent.com/101665566/161560575-2ef2ef2a-3fa9-48c9-818b-d9baee7137a1.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/161592945-f832b3e0-87c7-47ea-88c4-1963c13a0ccc.png)
@Katiemoser
