### ISSUE TITLE
PPC Landing Pages form response

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#412]
Can we please change the form response title to read "Thank you for submitting your information" (remove "agency"). This is for all PPC landing pages.

![image](https://user-images.githubusercontent.com/101665566/161775594-6c246ec5-d648-42db-bffe-1e69cebf62b1.png)

**Comment by darwin808** [comment]
![Screen Shot 2022-04-05 at 11 01 07 PM](https://user-images.githubusercontent.com/71545960/161784186-df5433f4-7fe7-42cb-ae19-9db5d69de73a.jpg)

**Comment by Katiemoser** [comment]
Approved, thank you!
