### ISSUE TITLE
Build Landing Page: Integrations

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#427]
**This will be a template for "Integrations-Individual Pages" in the manager (parented under "integrations": https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-88e5918e85-tmg13p

Please build out using the doc below that contains screenshots of components from this landing page (PPC Long Form): https://www.zesty.io/ppc/headless-cms/

Doc: https://docs.google.com/document/d/1Kf8nDSV4zyfL6qCKdR3NrU8t-6dY6Y7kGt8QZKGZKws/edit?usp=sharing

Please use this as the CTA (only one button at the top instead of two): https://github.com/zesty-io/nextjs-website#developer-codeblock-starter

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/162058755-c0bbedb0-3542-405f-a1f5-482ee6e0f7e8.png)
![image](https://user-images.githubusercontent.com/71545960/162058777-d8519e7e-02ab-4a2d-ace0-511040d15cc6.png)
![image](https://user-images.githubusercontent.com/71545960/162058795-bc9029c8-d399-4346-8205-ba4d2aeae009.png)
![image](https://user-images.githubusercontent.com/71545960/162058839-bda7fd73-ffac-4242-b74a-f176be866325.png)
![image](https://user-images.githubusercontent.com/71545960/162058880-f3b82e94-bcd5-40d5-8f09-eb9af179d285.png)
![image](https://user-images.githubusercontent.com/71545960/162058903-044c3d83-476d-4371-942e-cc33d85b2508.png)
![image](https://user-images.githubusercontent.com/71545960/162058929-189fa869-21a4-4eb2-98e7-013669fec523.png)
![image](https://user-images.githubusercontent.com/71545960/162058971-19c5c92f-c7d0-4509-855b-cc9a4012871a.png)
![image](https://user-images.githubusercontent.com/71545960/162059002-39778d87-761b-4dfc-9c3d-62d50a09f482.png)

**Comment by darwin808** [comment]
@Katiemoser I published it in manager for link to work 

https://kfg6bckb-dev.webengine.zesty.io/integrations/nextjs-cms/

**Comment by Katiemoser** [comment]
Edits below:
![screencapture-kfg6bckb-dev-webengine-zesty-io-integrations-nextjs-cms-2022-04-07-16_29_27](https://user-images.githubusercontent.com/101665566/162335949-2abd5572-b28d-462c-9903-dbee995587f0.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/162435083-acc00355-dd16-462d-9fbc-9d46eb27c954.png)
![image](https://user-images.githubusercontent.com/71545960/162435112-bafd8be3-c663-41e1-ab0e-59be4441f924.png)
![image](https://user-images.githubusercontent.com/71545960/162435134-4873aba4-25f7-4f21-9c64-fbcdd1a30c19.png)
![image](https://user-images.githubusercontent.com/71545960/162435160-3949838e-6c58-421f-bd82-ef1697cca3dd.png)
![image](https://user-images.githubusercontent.com/71545960/162435180-829aab72-e47a-4c0f-97b1-4c0e89fcef7a.png)
![image](https://user-images.githubusercontent.com/71545960/162435204-c2053c4d-8a1d-49bc-9ea8-03bf6aa5b929.png)
![image](https://user-images.githubusercontent.com/71545960/162435224-9b0f9f20-8b7b-4900-af06-aae67cbb10a0.png)
![image](https://user-images.githubusercontent.com/71545960/162435249-600977f5-abc7-4108-8c2b-aa732f4727c6.png)

**Comment by darwin808** [comment]
@Katiemoser  we can hide other words in cta or ?

**Comment by Katiemoser** [comment]
Page looks great. @ardeay - can you address Darwin's question about the CTA button? It's very large and I'd love to make it smaller. Can we hide any of the words in it?

@darwin808 - let's also cut down some of the padding on the left and right of the text in the button so it fits closer to the words. Can we also trying changing the color to Zesty blue? #497EDF

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/162480060-4afbf0ee-7a6f-49e9-8f82-8f2a90cb0dcb.png)

@Katiemoser

**Comment by Katiemoser** [comment]
Hmm nevermind, let's go back to the Zesty dark blue - #1B202C

Thanks Darwin! I'll follow up when I have the content and probably will have a few additional edits.

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/162481399-ffe91c57-189e-4647-a8df-f4b928309d2f.png)
@Katiemoser

**Comment by Katiemoser** [comment]
Approved, thank you!
