### ISSUE TITLE
Chatbox Size on Mobile

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/nextjs-website#430]
Got a response from the Zoho team on how to customize the size of our chat on mobile - @Katiemoser do you have a preference on size? Right now it takes up the whole window. 

From Zoho: `"You` can reduce the size of the chat window only in mobile browser with the help of our custom CSS. I've attached a sample CSS file herewith in which you can edit the height as per your requirement and add this to your website style sheet. 

This will decrease the size of the chat window only when accessed from mobile browser."

**Comment by chloespilotro** [comment]
`@media only screen and (max-width: 555px) and (min-width: 100px)
{
body div.zsiq-newtheme.zsiq-mobhgt[embedtheme] {
    height: 60% !important;
    width: 80% !important;
}
}`

**Comment by darwin808** [comment]
@chloespilotro hi what page is this so i can view

**Comment by chloespilotro** [comment]
Fixed chat toggle on mobile, style can remain the same.
