### ISSUE TITLE
Updates to /nextjs-cms/ page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#443]
Please see edits below:
![screencapture-zesty-io-integrations-nextjs-cms-2022-04-11-16_10_32](https://user-images.githubusercontent.com/101665566/162850205-1ba61caa-8cb1-4a24-946d-fc6d67497b2b.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/162918117-28794a86-03fa-49e8-9524-8198c4961e11.png)
![image](https://user-images.githubusercontent.com/71545960/162918177-c8361cc4-9ff2-4afe-b700-45236b964dc4.png)
![image](https://user-images.githubusercontent.com/71545960/162918212-e284381c-a2eb-4920-a5a5-b6aab3b228d1.png)
![image](https://user-images.githubusercontent.com/71545960/162918246-a3e402ef-8812-4476-9e4d-aeef296daeb0.png)
![image](https://user-images.githubusercontent.com/71545960/162918307-2a35f5d5-ee32-411b-afb8-16bd65c3f508.png)
![image](https://user-images.githubusercontent.com/71545960/162918339-be32d77b-7648-405d-85c2-964ba811ea47.png)
![image](https://user-images.githubusercontent.com/71545960/162918403-a077d91f-a920-4879-b1e6-2c4b8cfefdae.png)

**Comment by Katiemoser** [comment]
Looks awesome, thank you!
