### ISSUE TITLE
NextJS Landing Page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#449]
Please connect content to the schema (bottom sections). Change top CTA button back to Zesty dark blue with white text. Make the bottom CTA buttons match the "try free" and "schedule a demo" ones on the homepage.

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/163662244-88047fa7-9f33-49e6-88f1-cd0a5e3732d9.png)
![image](https://user-images.githubusercontent.com/71545960/163662250-f6c3c6f0-68d7-4747-a62a-5f44f213a2da.png)

**Comment by Katiemoser** [comment]
Hey Darwin, I mistyped the CTA button directions. Can we actually change the bottom button to match the line of code at the top? Make it orange instead of dark blue. Can we also remove the orange outline from the button at the top? Thanks!

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/163838839-08203763-8e94-4060-a110-9ad45f5c7710.png)

**Comment by Katiemoser** [comment]
Approved, thank you!
