### ISSUE TITLE
Headless CMS page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#450]
https://www.zesty.io/solutions/headless-cms/

Please fix padding on section below:

![image](https://user-images.githubusercontent.com/101665566/163631343-91f42458-4971-49c6-bff2-ebd6062cac9f.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/163662403-06510f47-54f2-475d-a4d5-fa505d6b3bff.png)

**Comment by Katiemoser** [comment]
Approved, thank you!
