### ISSUE TITLE
Homepage - case studies

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#46]
I want to be able to customize the image & copy on these cards instead of just pulling exactly what's on the article. Can we change how these are pulling?

**Comment by giseleblair** [comment]
@Katiemoser  yep we can do that. You'll want to create a relational field for it on the homepage too

**Comment by Katiemoser** [comment]
@giseleblair - okay all set - added to Homepage schema as "case study cards (new)". Let me know if there are any issues. Thanks!

**Comment by Katiemoser** [comment]
BTW we can use the styling of the case studies on the "customers" (/clients/) page if need be.
