### ISSUE TITLE
Next.js landing page changes

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#460]
Please see below:
![screencapture-kfg6bckb-dev-webengine-zesty-io-integrations-nextjs-cms-2022-04-20-10_12_58](https://user-images.githubusercontent.com/101665566/164287218-c3a802d3-4cf3-4c14-9ed9-b02e928a3dad.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164294989-0d420d1c-a921-4538-bff1-d10ffc47b18e.png)
![image](https://user-images.githubusercontent.com/71545960/164295000-45391b12-ad7a-4edc-ab7d-953d7ed84076.png)
![image](https://user-images.githubusercontent.com/71545960/164295018-cb018190-951a-4cbb-a0f9-13411b32ff82.png)
![image](https://user-images.githubusercontent.com/71545960/164295048-0998728a-ff36-4318-a646-ad70e506efaf.png)
![image](https://user-images.githubusercontent.com/71545960/164295070-91c078d7-92dc-4641-9147-b15a2c90fb14.png)
![image](https://user-images.githubusercontent.com/71545960/164295094-7a8316c6-fce7-48c6-a394-58456854e1da.png)
![image](https://user-images.githubusercontent.com/71545960/164295114-8b3cd1a1-71ba-4753-8635-695d49af51d0.png)
![image](https://user-images.githubusercontent.com/71545960/164295137-be0e6066-437b-48b7-bab0-0426893179a3.png)
![image](https://user-images.githubusercontent.com/71545960/164295165-dd9c490b-3c59-4418-8c43-3b00f8ce14ae.png)

**Comment by Katiemoser** [comment]
So fast!! Amazing work, thank you!
