### ISSUE TITLE
Pricing Page update

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#463]
Above the "$475/mo" and "$3,500/mo" can you please add the words "starts at" in small black text, left-aligned. Don't add above "custom".

![image](https://user-images.githubusercontent.com/101665566/164296704-eaf9f3fd-e801-4540-bec4-3b93e73e16f3.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164298561-b9b67302-9822-4617-a767-9ebd00cc63d3.png)

@Katiemoser

**Comment by Katiemoser** [comment]
Can we also put a space above "custom" so it sits on the same line as the others?

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164306167-599abdbe-da94-4b9b-a4aa-2f57f2d24f77.png)
@Katiemoser

**Comment by Katiemoser** [comment]
Approved!
