### ISSUE TITLE
explore.zesty.io landing page design update

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#464]
Can you please update this landing page to the new template/branding? You should have access now to the instance. Please also update the favicon to our new logo.

http://explore.zesty.io/

*****Note: this page is currently running in ads, so we need to make sure we don't push anything live until it's completely ready. Please only make changes in dev**

Below is the current landing page on the left and the component I'd like to use on the right. The top three components are from the homepage of Zesty.io, the one with the red lines is from /why-zesty/ and the form is from the Capterra landing page we just completed.

![Artboard 1](https://user-images.githubusercontent.com/101665566/164336173-d13f860a-2c71-45f6-b4f2-2e4cd868585e.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164544611-c4bda960-f966-4b28-a404-3bbe36e49717.png)
![image](https://user-images.githubusercontent.com/71545960/164544650-17656dfe-0cd2-4582-aa0b-0272a59733e3.png)
![image](https://user-images.githubusercontent.com/71545960/164544714-66f2c63a-dc12-4b06-89a7-51e08a2f678f.png)
![image](https://user-images.githubusercontent.com/71545960/164544731-b3d5d49e-4815-4259-b586-63abb150a4dd.png)
![image](https://user-images.githubusercontent.com/71545960/164544753-81c64dd9-8ef1-49a9-aa97-222384abb56e.png)
![image](https://user-images.githubusercontent.com/71545960/164544781-157e2b71-2ae1-4159-a0c1-180047e261b4.png)
![image](https://user-images.githubusercontent.com/71545960/164544806-0aad71d8-24b0-4fe2-8289-fb3497d0d566.png)
@Katiemoser

**Comment by Katiemoser** [comment]
Looks good. Can we make the icons grey instead of black? I will have additional edits, but I need to look at the page a little more closely. When you have the dev URL, can you send to me?

**Comment by darwin808** [comment]
@Katiemoser  

https://kfg6bckb-dev.webengine.zesty.io/ppc/explore/

**Comment by Katiemoser** [comment]
Thank you! Edits coming your way soon.

**Comment by Katiemoser** [comment]
Edits attached

![screencapture-kfg6bckb-dev-webengine-zesty-io-ppc-explore-2022-04-22-09_07_41](https://user-images.githubusercontent.com/101665566/164753728-17f1ebc8-ed7b-47c2-ba10-fa7bd8e3b347.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164764290-a31499ff-0d23-4072-9cac-b2f2317c9e54.png)
![image](https://user-images.githubusercontent.com/71545960/164764315-4438f375-9545-4ec2-88b7-4db578409e5a.png)
![image](https://user-images.githubusercontent.com/71545960/164764342-cee60bf4-98ef-4f91-847d-75839c7b14f2.png)
![image](https://user-images.githubusercontent.com/71545960/164764367-4ac8622a-11ce-4446-bf52-a3498eefa48c.png)
![image](https://user-images.githubusercontent.com/71545960/164764387-1517245a-9326-4228-bcaa-cd09c837e21a.png)
@Katiemoser

**Comment by Katiemoser** [comment]
Sorry, a few additional edits. Let's actually take out that title "join top companies" and just leave the logos. Everything else looks good for now, I will add some edits once I have the copy/images done. Thank you!!

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164766350-6c5d404d-c3a3-4c6c-a7df-81123585193d.png)
@Katiemoser I remove the title in logos

**Comment by Katiemoser** [comment]
Looks good, thank you!
