### ISSUE TITLE
Next.js landing page final changes

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#466]
Please change the video to this link: https://youtu.be/h9WMdlQyFgU?t=50

Please make the changes outlined below:
![screencapture-kfg6bckb-dev-webengine-zesty-io-integrations-nextjs-cms-2022-04-21-15_37_28](https://user-images.githubusercontent.com/101665566/164563134-6e8f8d81-c21c-44f8-bcd8-20e2a94a63e8.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164624641-ae295711-c51c-477b-9310-aaa709fcf8f7.png)
![image](https://user-images.githubusercontent.com/71545960/164624668-b579f3ec-2107-4774-b63e-8a89a5304e65.png)
![image](https://user-images.githubusercontent.com/71545960/164624701-1e732a3b-0653-4fb6-a580-d01ef8abc316.png)
![image](https://user-images.githubusercontent.com/71545960/164624712-1edca53d-3072-4192-bf9d-83cfd61fd4be.png)
![image](https://user-images.githubusercontent.com/71545960/164624735-f22c988b-3670-4e58-a0a8-dd88c9de6d6f.png)
![image](https://user-images.githubusercontent.com/71545960/164624762-94bb2d61-d4fb-4979-a548-cffdf68cf59f.png)
![image](https://user-images.githubusercontent.com/71545960/164624779-ebfaca3a-b065-4a4e-ab9f-74454871041d.png)
![image](https://user-images.githubusercontent.com/71545960/164624803-cd7c062a-a5f2-4227-bc92-d94a21430ab2.png)

**Comment by Katiemoser** [comment]
Looks great! The only change I have is for the review - can we change the title to be connected to "benefit above review' in schema? And then have the "senior web developer" be at the bottom where the name normally is in the component? Thanks!

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/164782188-b8b6789b-3bf9-4cf6-83a5-0b6fcb640483.png)
@Katiemoser

**Comment by Katiemoser** [comment]
Perfect, thank you!!!!
