### ISSUE TITLE
Quick change to Capterra form

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#468]
Please change the lead source to "advertisement".

Once this is done, can we please push this page live? Thanks!

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/165026786-3d6bebcb-c68d-45c7-8934-2d2fe8254ab8.png)


@Katiemoser

**Comment by Katiemoser** [comment]
Approved, thank you! Can you let me know when this goes live?
