### ISSUE TITLE
final changes to /ppc/explore landing page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#471]
Please see below
![screencapture-kfg6bckb-dev-webengine-zesty-io-ppc-explore-2022-04-25-10_23_24](https://user-images.githubusercontent.com/101665566/165142506-3e2c1a65-2ff3-4de5-94ec-0595455e0372.png)
:

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/165156023-2556de0d-59d0-454e-91f1-d2a878aab6b5.png)
![image](https://user-images.githubusercontent.com/71545960/165156043-86148bcd-6aed-442c-aeef-29423d69337e.png)
![image](https://user-images.githubusercontent.com/71545960/165156074-ecade755-617e-43e7-8256-beccfc1926a0.png)
![image](https://user-images.githubusercontent.com/71545960/165156110-5035868e-61af-4088-a70d-84886ac81546.png)
![image](https://user-images.githubusercontent.com/71545960/165156137-2ff042df-a3d2-4ace-a271-5d286fed01eb.png)
![image](https://user-images.githubusercontent.com/71545960/165156156-88072b6c-4513-4038-a1cc-6fe249978943.png)

@Katiemoser

**Comment by Katiemoser** [comment]
Approved! LMK when it's merged in the next PR and I'll send over any mobile edits. Thanks!
