### ISSUE TITLE
Solutions (previously "Platform/Product Overview") - header

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#49]
- Add in H1 as eyebrow
- change "zest" to orange
- 
![image](https://user-images.githubusercontent.com/101665566/158464660-3987b1a9-4b19-41a1-bb54-8b6aad3364e9.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_22-06-46111111](https://user-images.githubusercontent.com/71545960/158775307-bd79f56f-901b-4023-b1c6-6b9437cce57b.png)

hi @Katiemoser what text we will add 
-Add in H1 as eyebrow
