### ISSUE TITLE
Solutions (product/platform overview) - "Benefits Header"

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#50]
- Center description text
- Provide more spacing between each line of paragraph
- Remove eyebrow
- Make font grey to match fonts in the paragraphs below.

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_20-30-34](https://user-images.githubusercontent.com/71545960/158808877-82587756-52e2-46f6-81d8-f68179682ca5.png)
