### ISSUE TITLE
Solutions (platform/product overview) - features section

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#51]
Connect header of this section to "Features Header" schema and remove CTA button

![image](https://user-images.githubusercontent.com/101665566/158465750-6f7d0544-1532-41b0-9fd3-e620d5306106.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_17-10-50](https://user-images.githubusercontent.com/71545960/158555926-fb772099-03e4-468e-a688-3a7610d82ae6.png)

**Comment by Katiemoser** [comment]
Approved.
