### ISSUE TITLE
Website Instance Selector

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#514]
Build out https://github.com/zesty-io/nextjs-website/blob/main/src/components/console/AppBar.js to check for user authentication and login. If the user is not logged in,the app bar should show a link to login. If logged in it should show the instance selector and user avatar.

ZestyAPI shoudl load from fetch wrapper, already loaded in project <head>

The cookie: `APP_SID` is how you check is users is logged in
Selected instances: `ZESTY_WORKING_INSTANCE` is the cookie name

Have a dropdown "instance selector" with a search filter, this should show all ZestyAPI.getInstances(), the filter should search through names, zuids, when an instance is selected, the instance ZUID value should be stored to cookie `ZESTY_WORKING_INSTANCE`

If cookie `ZESTY_WORKING_INSTANCE` exists, it should show that as the selected instance in the dropdown by default, if no instance is selected, show "select an instance"

![image](https://user-images.githubusercontent.com/729972/169327380-68209dd8-b34f-4a13-b705-8af4d17b7895.png)

Selected State

![image](https://user-images.githubusercontent.com/729972/169334822-76ae5c15-49b1-4e8a-843e-58c037235298.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/169480275-a1db9cad-f9c0-4abe-9321-4fb12851e2a5.png)
![image](https://user-images.githubusercontent.com/71545960/169480315-179f14d9-5c40-461a-9960-35c97a127bb9.png)
![image](https://user-images.githubusercontent.com/71545960/169480430-a151afcd-8727-42b6-943a-c70e8e6b1e00.png)

**Comment by ardeay** [comment]
For avatar md5 [https://stackoverflow.com/questions/14733374/how-to-generate-an-md5-file-hash-in-javascript-node-js] hash the user email, then use `https://www.gravatar.com/avatar/'+user.emailHash`

**Comment by ardeay** [comment]
Please show selected instance state, and show cookie is stored with a screenshot of the cookie in developer tools

**Comment by ardeay** [comment]
You can get more user info using

```
		let thisUser = await ZestyAPI.verify()
		let userInfo = await ZestyAPI.getUser(thisUser.meta.userZuid)
```

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/169558180-abeb379b-9ec3-478e-89ed-debd4b54ed5f.png)
![image](https://user-images.githubusercontent.com/71545960/169558281-b564f677-5672-473f-824a-39e849332ba6.png)
![image](https://user-images.githubusercontent.com/71545960/169558334-201ef250-1be5-49d5-b092-17676b9bd8b3.png)
![image](https://user-images.githubusercontent.com/71545960/169558414-cd5af099-dd0d-4b9c-b97f-52e78706af83.png)

**Comment by ardeay** [comment]
nice, please push to PR and send me link @darwin808 thanks
