### ISSUE TITLE
Solutions - (product/platform overview) - styling of "case studies" section

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#52]
Please make header an H2 styling.

![image](https://user-images.githubusercontent.com/101665566/158467691-84438503-5efd-4d73-9c92-23311c3242db.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_17-11-55](https://user-images.githubusercontent.com/71545960/158556108-038fe017-4e58-4a06-9179-78b6e6fb8b0b.png)

**Comment by Katiemoser** [comment]
Approved.
