### ISSUE TITLE
Marketplace SEO Meta Tags

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#529]
Use meta.title meta.description for meta title and description, og title and og description

Use the marketplace content item placard for og:image, use placard image, use zesty OTF https://zesty.org/services/media-storage-micro-dam/on-the-fly-media-optimization-and-dynamic-image-manipulation to crop the image to OG image standard 1200:630 px

**Comment by ardeay** [comment]
ZestyHead maybe able to be referenced https://github.com/zesty-io/nextjs-website/blob/main/src/components/ZestyHead.js

**Comment by glespinosa** [comment]
![image](https://user-images.githubusercontent.com/44116036/169860531-a52dcc8a-00c3-494b-addc-4debec0cf14b.png)
