### ISSUE TITLE
Solutions (product/platform overview) - benefits section images

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#53]
Images need to be connected, not loading when I update.

![image](https://user-images.githubusercontent.com/101665566/158468222-4508af7c-faae-4769-a1a4-7925fc321090.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_17-20-08](https://user-images.githubusercontent.com/71545960/158557606-0179e122-d7ab-4c3a-8961-7f49e6f0441a.png)
