### ISSUE TITLE
Add phone number to this form

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#537]
Please add phone # to the form on this page & make it map to phone number in Zoho.

https://www.zesty.io/dxp-rfp-template/

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/169947030-062daad9-bdc2-471d-97af-19e0a269c070.png)
![image](https://user-images.githubusercontent.com/71545960/169947109-df0b6538-ee22-4a34-92c2-252a0dbb346b.png)
