### ISSUE TITLE
Phone numbers on forms

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#542]
Please add a phone number field to the forms on all these pages:
zesty.io/ppc/headless-cms/
zesty.io/ppc/headless-cms-demo/
https://www.zesty.io/ppc/digital-experience-platform-demo/
https://www.zesty.io/ppc/digital-experience-platform/
https://www.zesty.io/ppc/content-management-system-demo/
https://www.zesty.io/ppc/content-management-system/

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/170266591-7d984fb3-68fa-493d-8071-c2332f676d31.png)
![image](https://user-images.githubusercontent.com/71545960/170266729-f3b2137e-2353-45ed-b4c9-3483fbaa4bdf.png)
