### ISSUE TITLE
Docs Navigation filter

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#544]
Make the docs navigation work like the nextjs docs 

Live example https://nextjs.org/docs

![image](https://user-images.githubusercontent.com/729972/170289483-9abadad3-6a30-4e37-ad6d-4a209ce1f99d.png)

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/170482920-a8fe15e4-dee2-4517-9776-c93b53465e13.png)
![image](https://user-images.githubusercontent.com/71545960/170482977-7695e75c-b957-4b3e-b31f-1a79811dd8f2.png)
![image](https://user-images.githubusercontent.com/71545960/170483006-8daa023a-7bcd-4e2c-880c-70967e2084eb.png)
![image](https://user-images.githubusercontent.com/71545960/170483030-b2e8c438-c118-468f-9909-23a4f7976724.png)
