### ISSUE TITLE
Why Zesty.io - header

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#56]
Style with light blue grey background similar to homepage.

![image](https://user-images.githubusercontent.com/101665566/158468810-6f98e941-94e0-45d7-8b4a-8e5d0bc7f763.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_17-39-43](https://user-images.githubusercontent.com/71545960/158561214-b384b0af-928d-4e45-bf55-e74938c92e49.png)

**Comment by Katiemoser** [comment]
Approved.
