### ISSUE TITLE
Thank you page for simple form

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#574]
When a form is filled out, an pop up happens now, please change the simple form to a landing page `/thank-you/` @Katiemoser please confirm the desired URL.

**Comment by Katiemoser** [comment]
please make the URL /ppc/thank-you. I'd like the content to be dynamic based on what page they come from, is that possible @ardeay ? Or should I make separate TY pages for each page. Reasoning is that I'd like to provide content related to the page they come from (DXP, CMS, headless, etc)

**Comment by Katiemoser** [comment]
@jomarmontuya - You can use the header from the ppc-long form pages (pic below). Here is the schema: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-cef69cdc8d-06vzcd/7-9cbec1fe83-ckkhqn

I'd like the articles to be the style that Roz designed for the headless CMS page (also pic below).

![image](https://user-images.githubusercontent.com/101665566/172732892-515c14a9-a869-4170-81bd-a4ed2a494c10.png)

![image](https://user-images.githubusercontent.com/101665566/172732913-1b06bd8f-c96e-4817-b350-c395aa935b87.png)

**Comment by Katiemoser** [comment]
@jomarmontuya - can you reduce padding between top section and industry insights section? thanks!
