### ISSUE TITLE
Why Zesty.io Benefits section - flip middle portion image & text

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#58]
Make "Let our automation" portion flip so that image is on left & text is on right. *****DO NOT CHANGE IN MOBILE**

![image](https://user-images.githubusercontent.com/101665566/158469425-fc66c05e-731d-4256-96d8-7d63a5e65895.png)

**Comment by Katiemoser** [comment]
@darwin808 - can we switch the top and bottom sections back to the right? Only the middle portion should be image left-text right.

Also, can we remove the phone graphic so that the image shows up like it should?

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_03-39-18](https://user-images.githubusercontent.com/71545960/158676273-70bf09ce-f09e-48b6-9a2f-f35ea356a33e.png)

the phone graphic is the fallback image if the image from endpoint is undefined

**Comment by Katiemoser** [comment]
Approved.

**Comment by Katiemoser** [comment]
@darwin808 - I updated the top image (the guy with the laptop) but it's still showing in the phone. can we fix that?

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_16-48-51](https://user-images.githubusercontent.com/71545960/158772011-4fe880d5-a7f5-4fb5-870e-409f9b6d993e.png)
@Katiemoser
