### ISSUE TITLE
Why Zesty - more than headless solution

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#59]
Make styling match component on homepage (in process of being updated - has an icon). Make background light blue/grey

Current:
![image](https://user-images.githubusercontent.com/101665566/158469505-5a31861d-b363-490e-90b6-32337da103fa.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_20-41-48](https://user-images.githubusercontent.com/71545960/158810605-0269efa1-a00a-49ee-9192-b7eccc93fa83.png)
