### ISSUE TITLE
Why Zesty - proof in numbers

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#60]
- Remove boundary boxes from each card and spread out so that the margins match the text margins of the rest of the page.
- Make sure icons pull through

![image](https://user-images.githubusercontent.com/101665566/158469763-1e3e358d-6007-409d-98b4-acc76a43851d.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_20-47-43](https://user-images.githubusercontent.com/71545960/158593220-a421e143-18b8-4d80-916c-3be11c566c58.png)
