### ISSUE TITLE
Why Zesty - rocket league case study

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#61]
Make background grey 

![image](https://user-images.githubusercontent.com/101665566/158469828-97e85c70-9ac0-4a39-902c-6d5a576006df.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_20-51-52](https://user-images.githubusercontent.com/71545960/158593946-07bb6e5b-cfae-4ec6-a9b0-94d1b9740f59.png)

**Comment by Katiemoser** [comment]
Let's have the image still span the the whole way like in the original, just make the left side grey (and line up the top and bottom with the image)

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_02-21-20](https://user-images.githubusercontent.com/71545960/158660576-0d979bfe-1c29-4ae3-aa5d-b5859566f90e.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_02-24-20](https://user-images.githubusercontent.com/71545960/158660887-78d91657-942b-4e9e-96ea-7efb173d3a31.png)

**Comment by Katiemoser** [comment]
Can the image line up with the top and bottom of the grey so there's no padding above or below the image?

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_03-29-14](https://user-images.githubusercontent.com/71545960/158674610-0ddcd656-68bc-4b04-af2b-60964eed017b.png)
