### ISSUE TITLE
Headless CMS page edits

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#613]
For this URL - /solutions/headless-cms/

**Header:** Please keep styling but make "headless cms" the H1 and the line below it the H2
![image](https://user-images.githubusercontent.com/101665566/174189866-fa624c4b-0f01-46b0-91a3-bac2941a49fa.png)

Apostrophe is not coming up correctly (is correct in WYSIWYG)
![image](https://user-images.githubusercontent.com/101665566/174190020-cb829c43-3d5e-474c-a163-3639f0e43428.png)

Move "integrations" section above "industry insights" and "brands that trust Zesty"

For the articles at the bottom, can we make the titles NOT register as H3s? Possibly H4s instead but keep the styling?

**Comment by jomarmontuya** [comment]
Hi @Katiemoser this is complete please see PR Here -> https://github.com/zesty-io/nextjs-website/pull/629
