### ISSUE TITLE
marketplace register page form need to be hidden if not verified logged into zesty 

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#619]
https://www.zesty.io/marketplace/register/
![image](https://user-images.githubusercontent.com/729972/174841398-02d8ba92-95cd-4c92-ad0c-f9c96356e486.png)

Hide that form is not verified

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/174844597-13707d62-6ac1-45a0-b519-9cfb64795001.png)
![image](https://user-images.githubusercontent.com/71545960/174844772-71597d0a-1c57-465c-ae7a-b6548837c24d.png)
