### ISSUE TITLE
Headless CMS (tech overview) - proof points

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#67]
- Remove header text
- Make icons render

![image](https://user-images.githubusercontent.com/101665566/158471257-d47332f2-94b0-477c-9533-cef3cfb22197.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_21-39-09](https://user-images.githubusercontent.com/71545960/158602710-51440c41-9d7d-48ff-895f-22986534ecf4.png)

#note
data in here is static cant find benefits in endpoint/api

**Comment by Katiemoser** [comment]
@giseleblair - there is a headless component called "Technology benefits" and in there is a section for "icon_name" - lmk if we need to build this a different way.

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-8afa89aae1-4c9xdt
