### ISSUE TITLE
Global padding issues

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#679]
Padding on all of Zesty.io is off. We need to make check the global padding for the pages and make sure it is standard, larger than what is there now. I've pasted a few examples below but this affects the entire site. 

**However, please make sure that this update does not adversely affect the following pages: /solutions/headless-cms/ ; /solutions/hybrid-cms/ ; /solutions/digital-experience-platform/**

![image](https://user-images.githubusercontent.com/101665566/177886605-4b783f7e-a2db-4e76-a27d-9b21e88ed8d3.png)
![image](https://user-images.githubusercontent.com/101665566/177886631-5e26ba53-c4e7-487c-9e0b-c8974458dc5a.png)
![image](https://user-images.githubusercontent.com/101665566/177886644-aa3fdfb4-ef84-4228-ac33-c6aab942735a.png)
![image](https://user-images.githubusercontent.com/101665566/177886659-20a978af-a08e-4a9d-a90e-ff256b7d657b.png)
![image](https://user-images.githubusercontent.com/101665566/177886676-2664f4cf-bd9d-436c-9bb5-43dfc1aad2d8.png)
![image](https://user-images.githubusercontent.com/101665566/177886695-1943a20d-0121-46df-83b5-ae5b44a88a50.png)
![image](https://user-images.githubusercontent.com/101665566/177886713-971b8df5-ef9b-4376-8fb5-cf0e5fdb4c04.png)

**Comment by jomarmontuya** [comment]
@Katiemoser  PR is up  for this issue -> https://github.com/zesty-io/nextjs-website/pull/687

**Comment by jomarmontuya** [comment]
Resolved - > https://github.com/zesty-io/nextjs-website/pull/687
