### ISSUE TITLE
Headless CMS (tech overview) - features list

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#68]
Style like original & make background light blue/grey

Current
![image](https://user-images.githubusercontent.com/101665566/158471492-3d714819-adb8-4e22-a9da-1d87ee9786b7.png)

Original 
![image](https://user-images.githubusercontent.com/101665566/158471513-ca54ebb6-cd8e-42c5-9b2d-369d5389ab05.png)

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_04-21-39](https://user-images.githubusercontent.com/71545960/158684279-4142b70d-4c08-4fb7-b067-72f6cc300e7c.png)

featured_image is null 
gray text can be set in cms
