### ISSUE TITLE
Headless CMS (tech overview) - quote at bottom

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#70]
Make match original styling (text centered) and make background white.

current
![image](https://user-images.githubusercontent.com/101665566/158472246-0435f204-bf3c-486e-917e-5db26acfc4a0.png)

original
![image](https://user-images.githubusercontent.com/101665566/158472214-22d8302d-554d-4490-b9be-ef3c2e6fe6bd.png)

**Comment by darwin808** [comment]
@Katiemoser this can be edit in cms or in client ?

**Comment by Katiemoser** [comment]
I don't think I have control over styling

**Comment by darwin808** [comment]
![fdfgefweffd131](https://user-images.githubusercontent.com/71545960/158854305-45329549-2a83-4057-b579-eecaf0e2980e.png)

**Comment by Katiemoser** [comment]
approved.
