### ISSUE TITLE
Form updates to gated content pages

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#700]
Please update the forms to the following:

**Headless CMS Buyers Guide: https://www.zesty.io/headless-cms-buyers-guide-and-rfp-template/
- <iframe frameborder="0" style="height:500px;width:99%;border:none;" src='https://forms.zohopublic.com/zestyio/form/MACDFHeadlessCMSBuyerGuide/formperma/85G2GzuN9JB6x7vw_n_Q_YX6CNn5W3fg7KBOY0aH6wI'></iframe>

**DXP buyers guide: https://www.zesty.io/dxp-rfp-template/
- <iframe frameborder="0" style="height:500px;width:99%;border:none;" src='https://forms.zohopublic.com/zestyio/form/MACDFDXPbuyerguide/formperma/yoMgskMjct8uSU8QZnC1j0YJ_G77DCZN9bhE39k6Hts'></iframe>

**Scale whitepaper: https://www.zesty.io/whitepaper-scale/
- <iframe frameborder="0" style="height:500px;width:99%;border:none;" src='https://forms.zohopublic.com/zestyio/form/MACDFScalewhitepaper/formperma/hUyiU657xyWRXSXcHgnkj-PWK-hzstCWFhtST0TCx4o'></iframe>

**Comment by ardeay** [comment]
@jomarmontuya there is a component for this, and an example, please see the PPClongform page for reference

**Comment by jomarmontuya** [comment]
https://github.com/zesty-io/website/pull/713
