### ISSUE TITLE
State error for Accounts

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#704]
The update to AppBar to use the state object is creating a infinite loop between the rerender and state setting, triggering the app to crash

![image](https://user-images.githubusercontent.com/729972/180312240-47832481-ce0d-429c-bde2-60cf202d6f8a.png)

![image](https://user-images.githubusercontent.com/729972/180355213-3ec839de-8885-4544-aa5a-12ffca5e07fe.png)

**Comment by darwin808** [comment]
@ardeay 

## Error 

### Url : http://test.zesty.io:3000/marketplace/

![image](https://user-images.githubusercontent.com/71545960/180371306-36de5562-2646-4234-a736-f22e972cd58b.png)
![image](https://user-images.githubusercontent.com/71545960/180371324-00543f22-7f41-4b70-a1ee-70f851920e9d.png)

## Fix 

![image](https://user-images.githubusercontent.com/71545960/180371500-e27ec7ea-874d-42b1-8484-21f83451f109.png)
![image](https://user-images.githubusercontent.com/71545960/180371517-02b0e904-14d8-43ba-888d-21b724f98c15.png)

## Why? 

Executing a setState triggers a re-render, so we should never have a setState inside the render method, or else an infitine loop happens instead we can wrap it inside a function to prevent infinite loop.
