### ISSUE TITLE
Marketplace: updates

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#707]
In the Marketplace instance, each entities item will have a value for "available" which can be 1,0, or null. 

If available !=1: display a banner on the entity card that says "Coming Soon". On the entity's page, add a header that says "Coming Soon" and disable the install button. 

On the Marketplace homepage: iterate through the Featured Entities which will come from the Marketplace component with the field name of featured_entities

Each entities item will have a toggle value for "recommended", add a pill tag that says "Recommended" only if that value is equal to 1.

**Comment by jomarmontuya** [comment]
Coming Soon Pill -> 
![image](https://user-images.githubusercontent.com/61284357/180771792-0d9eb457-8dbf-421a-b263-29b3ba6c9ae2.png)

Single Page -> 
![image](https://user-images.githubusercontent.com/61284357/180771889-058acde5-b80f-4a9f-8baf-845a60a61cfe.png)

Featured Apps ->
![image](https://user-images.githubusercontent.com/61284357/180771933-47fc432f-3f1b-4ece-a9a6-942889875800.png)


@giseleblair please let me know if we need to change the layout of the pill and the banner for single page
