### ISSUE TITLE
Accounts: Profile page

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#715]
![image](https://user-images.githubusercontent.com/729972/180826282-01985244-5594-4aad-b7e9-2079aa5aee7d.png)

make each section into a tab, like the instances page is setup now 
![image](https://user-images.githubusercontent.com/729972/180826544-f4c2df14-d0b3-4bff-bea2-06392d96bb97.png)

Connect the data and do the save states

**Comment by bltarkany** [comment]
accounts & user profile wireframe:
https://drive.google.com/file/d/1_laTDKmb9VxFLqy02DntEMT2DvgRzbe1/view?usp=sharing

**Comment by ardeay** [comment]
- make profile icon in AppBar link to the profile 
![image](https://user-images.githubusercontent.com/729972/181017970-a55af4a7-a659-4eec-a264-114e278b13a8.png)
- header for instance is showing in profile 
![image](https://user-images.githubusercontent.com/729972/181018101-7dbc6406-8d27-4bdd-98bc-f1bfdd79ccdf.png)
- Profile needs a header, which include a larger edition of the user image, users name and email
- input with existing values should be prefilled with their value, for example the user name first and last input 
![image](https://user-images.githubusercontent.com/729972/181018381-66af8807-45cc-4146-906a-9a2f790ff6d9.png)
- on email view, existing emails should load in a MUI table
![image](https://user-images.githubusercontent.com/729972/181018520-6260f9d3-f7fd-4cee-b9fe-b4d936da7518.png)
- add spacing around input using FormControl with MUI https://mui.com/material-ui/react-text-field/#input-adornments 
![image](https://user-images.githubusercontent.com/729972/181018848-db4c3456-3196-4183-b336-8048c9a7298f.png)
- add icons to the input, like password, use the lock
- upon passwrod success, pop up success modal, with a logout button, (automatically log them out after 20 seconds)

**Comment by ardeay** [comment]
Make preferences a table
![image](https://user-images.githubusercontent.com/729972/181019593-431737a8-d223-4d65-bf63-e26d6742d2c6.png)


Preference Name | Description | Action (input)
Manage Teams | show or hide teams | [yes|no]

**Comment by ardeay** [comment]
Add save button to preferences, track dirty state, show green button when there is a change
