### ISSUE TITLE
Create new /demo-video/ page

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#724]
We would like to create a quick page to house a demo video. Please use the following page to create the content:
https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-a8d087aee5-x6n8r3/7-b0dbd7e2e8-m75ns3

Here are the components that we can use for each section from the MUI template:

- Header (instead of graphic please use video embed): https://thefront.maccarianagency.com/blocks/heroes - ./src/blocks/heroes/HeroWithLogoGridAndDesktopScreenshot/HeroWithLogoGridAndDesktopScreenshot.js|ts
- Form section: use something like this with the form from /demos/ on the right, no CTA buttons: https://thefront.maccarianagency.com/blocks/cta - ./src/blocks/cta/CtaWithIllustration/CtaWithIllustration.js|ts

**Comment by jomarmontuya** [comment]
@Katiemoser  layout is ready for your review -> https://github.com/zesty-io/website/pull/728
