### ISSUE TITLE
Marketplace styling update

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#732]
1) Images/gif asset in wysiwyg extends past the container: 
https://kfg6bckb-dev.webengine.zesty.io/marketplace/apps/page-layout-designer/

Solution: keep img assets from the wysiwyg as max-width:100%

2) Featured cards do not link to their page:
https://www.zesty.io/marketplace/

**Comment by jomarmontuya** [comment]
@giseleblair  https://github.com/zesty-io/website/pull/734
