### ISSUE TITLE
Developer Resources

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#74]
- Links need to open in new tab
- Make links text that says something like "see more" or "learn more" (editable) that are hyperlinked, instead of showing full URL

![image](https://user-images.githubusercontent.com/101665566/158473391-662a6f56-be98-42e3-ace7-a81194158233.png)

**Comment by bltarkany** [comment]
comment in google sheet asks for "Access Now -->" instead of URL. Is this the preferred verbiage?

**Comment by Katiemoser** [comment]
Yes please

**Comment by bltarkany** [comment]
arrows look a little funky, want me to remove them:
![image](https://user-images.githubusercontent.com/50595614/158902273-b8732d6b-28fa-49cd-a56d-ab3977ea68ea.png)
