### ISSUE TITLE
Marketplace: Apps missing descriptions

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/nextjs-website#747]
The listing page for apps shows the cards as them "missing description info"
![image](https://user-images.githubusercontent.com/208819/182202302-570120de-fe6f-44a0-b77b-de0ba940d67a.png)

**Comment by jomarmontuya** [comment]
![image](https://user-images.githubusercontent.com/61284357/182417192-d24fb7b1-4906-4f85-a66a-c2b06fc2e0e3.png)


https://github.com/zesty-io/website/pull/752

**Comment by jomarmontuya** [comment]
PR is up for this issue
