### ISSUE TITLE
Marketplace: App listing links not working

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/nextjs-website#748]
When clicking on a listing card in the [marketplace apps list view](https://kfg6bckb-dev.webengine.zesty.io/marketplace/apps/?instanceZUID=8-f48cf3a682-7fthvk) it does not take me to the individual app listing page as expected. Instead I am directed to the zesty.io homepage.

**Comment by jomarmontuya** [comment]
https://github.com/zesty-io/website/pull/752

**Comment by jomarmontuya** [comment]
PR is up for this issue
