### ISSUE TITLE
About Zesty - header

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#75]
Connect description with what's in Manager

![image](https://user-images.githubusercontent.com/101665566/158473582-9ce08b66-cb8b-48a3-a326-e84ea456d9b4.png)

**Comment by bltarkany** [comment]
about stats for this page needs content update in the manager
![image](https://user-images.githubusercontent.com/50595614/158900657-038384b7-2583-414c-9276-efc8f33d6da8.png)

**Comment by Katiemoser** [comment]
I will update.
