### ISSUE TITLE
Partner Page

### ISSUE THREAD

**Issue by carmengomezz** [zesty-io/nextjs-website#761]
Hi @jomarmontuya,

Please develop this page: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-fea599839a-22hv90/7-94d1dcd09d-dk6xj5
Using the attached template from: https://thefront.maccarianagency.com/logistics

Develop page as screenshots follow:
Header: 
<img width="636" alt="Screen Shot 2022-08-05 at 10 33 34 AM" src="https://user-images.githubusercontent.com/110561354/183137594-40a48060-595c-42a3-a0d6-4df4c02e82c9.png">
Why Zesty:
<img width="668" alt="Screen Shot 2022-08-05 at 11 19 52 AM" src="https://user-images.githubusercontent.com/110561354/183138117-1553abe1-f921-4ff6-a294-9e30abee64b3.png">
Logos:
<img width="766" alt="Screen Shot 2022-08-05 at 11 06 55 AM" src="https://user-images.githubusercontent.com/110561354/183138155-69fc800f-0221-46c2-b129-4cabfefe120c.png">
Benefits:
<img width="709" alt="Screen Shot 2022-08-05 at 11 18 13 AM" src="https://user-images.githubusercontent.com/110561354/183138246-b42acc66-c94b-4aa9-b46b-08c4af9dc7ae.png">
Testimonial:
<img width="625" alt="Screen Shot 2022-08-05 at 10 34 53 AM" src="https://user-images.githubusercontent.com/110561354/183138268-728885b0-2216-42f6-b14d-07d636c2949b.png">
End CTA (remove cards):
<img width="720" alt="Screen Shot 2022-08-05 at 11 06 27 AM" src="https://user-images.githubusercontent.com/110561354/183138426-62165e9e-bd82-4873-9795-2116c12ade13.png">

Thank you!

**Comment by jomarmontuya** [comment]
Hi @carmengomezz, just one quick question regarding the benefits section. is the 3 opentext area field from here _> https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-fea599839a-22hv90/7-94d1dcd09d-dk6xj5 
going to be used on  those box with images? just wanted to confirm that since the schema don't seem to fit on content. 

Please advise
CC: @Katiemoser

**Comment by Katiemoser** [comment]
@jomarmontuya looks like we may need 4 boxes, can we do two rows of two across? or four across, whichever looks better

**Comment by jomarmontuya** [comment]
![image](https://user-images.githubusercontent.com/61284357/185628760-c8e3fcb4-e37f-495f-a266-7ee3ccf20f65.png)


@Katiemoser, I'm thinking a layout something like this, what's your thought?

**Comment by Katiemoser** [comment]
Sure, let's go with it!

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/agency-partners/partner-program-benefits/
