### ISSUE TITLE
Demo video page update

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#772]
I'd like two changes to this page:

1. Would we be able to embed the module that's [on this page](https://www.zesty.io/meet/) to schedule a meeting rather than a form? If so, let's move the header "schedule 45 min" to the middle and put it above the module. 
2. Either way, let's remove some of the padding above the "schedule 45 min" header so that it's above the fold.

**Comment by jomarmontuya** [comment]
![screencapture-localhost-3000-demos-video-2022-08-10-18_57_44](https://user-images.githubusercontent.com/61284357/183885029-2247701e-e74d-4b83-9238-541a5859f1c1.png)


Here's the updated version @Katiemoser, I tried to not center the header cause of the bullet point it won't look nice on centered 

like so

![image](https://user-images.githubusercontent.com/61284357/183885268-447bef83-11fb-444b-90ad-d5fea4bcfb35.png)

**Comment by jomarmontuya** [comment]
let me know your thoughts about that
