### ISSUE TITLE
Resources hub

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#773]
Please develop a resources hub page based on this template - https://thefront.maccarianagency.com/blog-search

Manager link:
https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-c6dd93f5f2-qpdc9t/7-8cf8f09ff5-sx5pqs

![Content resources](https://user-images.githubusercontent.com/101665566/183746025-f18a51b6-55bb-4aaf-9387-da8bc1305409.png)

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/content-resources/
