### ISSUE TITLE
New page - DXP features

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#775]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-f686a0abe7-8zs3jw/7-d8aae8b2ea-kkd2br

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/
