### ISSUE TITLE
New Page - Headless CMS Benefits

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#777]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-c48bd087c0-5xvl6s/7-c0afcac8a4-66cskk

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/solutions/headless-cms/headless-cms-benefits/
