### ISSUE TITLE
New Page - Multi-site management

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#778]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-a4f2ed849b-r1cwpc/7-88a993b59f-kxh3kb

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/multi-site-management/
