### ISSUE TITLE
New page - Headless SEO

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#779]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-d8a3c1f48c-ztbs3n/7-ecb7a6818f-hdp3zq

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/seo/
