### ISSUE TITLE
New page - headless CMS features

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#780]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-b0ad9acbea-721hmm/7-f6f3ffc7ec-rcznxd

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/headless-cms/
