### ISSUE TITLE
New page - scalable CMS

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#781]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-fecf91e7e6-40xgbb/7-f8b5a5ece9-48hprf

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/elastic-scalability/
