### ISSUE TITLE
New page - localization

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#782]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-ee89a9ecc8-n5f7nv/7-b2f8c4f6cc-8gp6cv

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/localization/
