### ISSUE TITLE
New page - headless CMS for blog

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#784]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-9ec9addca6-1qp373/7-aabbf3eba8-92mh08

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/solutions/headless-cms/blogs-editorial/
