### ISSUE TITLE
New page - for marketers

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#785]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-acf4d8f2c3-s74mjg/7-869daedba9-mz87mt

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/use-case/marketers/
