### ISSUE TITLE
New page - for developers

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#786]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-a8aae6c2b5-n019mw/7-e89bc1d5b8-7m2qsh

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/use-case/for-developers/
