### ISSUE TITLE
New page - multi-language

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#788]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-e8dff7d0a0-np3tcx/7-a4e8c0cea2-bd9ptd

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/multi-language/
