### ISSUE TITLE
New page - for publishing

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#790]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-90988ca186-21hv0d/7-84f4f5a3cf-72wh92

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/use-case/digital-publishing-cms/

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-acf4d8f2c3-s74mjg/7-d2d9d882d3-nqp2cb
