### ISSUE TITLE
New page - for insurance

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#791]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-90988ca186-21hv0d/7-f6f8c58ccc-ztkhnt

**Comment by jeromeZestyIO** [comment]
http://zesty.io/use-case/insurance-cms/

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-acf4d8f2c3-s74mjg/7-98aadd84dc-k7rtr3
