### ISSUE TITLE
New page - for gaming

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#792]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-90988ca186-21hv0d/7-e4bc84afeb-htnvw6

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/use-case/gaming-cms/

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-acf4d8f2c3-s74mjg/7-dca3f4afc3-67d595
