### ISSUE TITLE
New page - for sports

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#794]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-90988ca186-21hv0d/7-f284988d9f-zc7t66

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/use-case/zesty-for-sports/
https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-a8aae6c2b5-n019mw/7-9eda9f88ea-krghfv
