### ISSUE TITLE
New page - headless enterprise

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#795]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-e6b7919994-n8p7t0/7-ccb1b589e9-77tfc2

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/solutions/headless-cms/enterprise-headless-cms/
