### ISSUE TITLE
New page - CDN hosting

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#796]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-ca81d1fdf3-vf07cl/7-d8c2c59ff7-qcpmlc

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/cdn-hosting/
