### ISSUE TITLE
New page - headless CMS for mobile

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#797]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-aa8c89f8a1-18dzf9/7-9af4a780a5-sgnqzr

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/solutions/headless-cms/headless-mobile/
