### ISSUE TITLE
New page - digital governance

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#798]
https://www.figma.com/file/iETaF6c8BJGKKvbFuy3NV9/ZESTY-PAGES-DESIGNS?node-id=0%3A1

https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-a2d18de8e7-cvf80c/7-80ced48eeb-4h6kmh

**Comment by jeromeZestyIO** [comment]
https://www.zesty.io/features/digital-governance/
