### ISSUE TITLE
Why Zesty - missing component

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#85]
Missing "Overview of Process" portion from Word Doc

Link to component: https://thefront.maccarianagency.com/
![image](https://user-images.githubusercontent.com/101665566/158477027-1a921877-49c1-4227-91c4-1f6a8c11c0f3.png)

**Comment by Katiemoser** [comment]
Sorry, wrong screenshot posted for me. What you posted is correct - the box with the HTML. Thank you! Approved.

**Comment by darwin808** [comment]
Hi @Katiemoser  this can be edit in cms platform

**Comment by Katiemoser** [comment]
@darwin808 - it's selected as a paragraph in the CMS, but it's rendering as different styling. I'd like the styling to match the screenshot without it being an H2.

**Comment by darwin808** [comment]
Hi @Katiemoser  can you edit the cms then put a style in the paragraph so that it will not become h2

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_20-18-19](https://user-images.githubusercontent.com/71545960/158806954-45782308-b4dd-4985-ac14-40048b0b8dc8.png)
