### ISSUE TITLE
Accounts: login

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#859]
![image](https://user-images.githubusercontent.com/729972/186173833-4f3af126-0a35-4ce3-8751-512ac35e70a0.png)

**Comment by ardeay** [comment]
Use these endpoint to populate
https://kfg6bckb-dev.webengine.zesty.io/login/?toJSON
https://www.zesty.io/login/?toJSON

**Comment by ardeay** [comment]
Modify the existing login component to do this, that way a logged out user see it anywhere there were

**Comment by ardeay** [comment]
Note, please add `views/zesty/Login.js` and load the component there too

**Comment by ardeay** [comment]
This will be a default view in zesty for /login/ as a direct path, but also will load the component on the page you were at (like we do in instances and profile) as a component

**Comment by ardeay** [comment]
For mobile, ipad size, hide the announcement and just show login

**Comment by giseleblair** [comment]
Need:

- [ ] Log out
- [ ] Reset password
- [ ] Microsoft SSO
