### ISSUE TITLE
[MOBILE] Author pages - all

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#87]
Headshot is overlapping name on mobile.
![Screenshot_20220315-144514_Chrome](https://user-images.githubusercontent.com/101665566/158478032-951365e8-688a-41ca-b89e-e8f3b30a5172.jpg)

**Comment by darwin808** [comment]
![Screenshot_2022-03-16_22-14-01](https://user-images.githubusercontent.com/71545960/158609781-c48a88fb-4639-4ed4-8c15-5e1125b4fa4f.png)
