### ISSUE TITLE
Instances: Support Tab

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#873]
Need ZOHO endpoints to build out the interface

Todos

- [ ] Create ticket api endpoint
- [x] Fetch tickets api endpoint
- [ ] Submit wireframe for UI development

**Comment by giseleblair** [comment]
- list all tickets: `fetch(`https://desk.zoho.com/api/v1/tickets?departmentId={{dept_id}}&fields=cf_instance_zuid`, { method: 'GET', headers:{"Authorization": "Zoho-oauthtoken " + zohoAccessJSON.access_token} })`

- list all tickets based on instance zuid:`fetch( https://desk.zoho.com/api/v1/tickets/search?customField1=cf_instance_zuid%3A{{instance_zuid}}*`, { method: 'GET', headers:{"Authorization": "Zoho-oauthtoken " + zohoAccessJSON.access_token} })`

- search for contact by email: `fetch(`https://desk.zoho.com/api/v1/contacts/search?email={{user_email_encoded}}`, { method: 'GET', headers:{"Authorization": "Zoho-oauthtoken " + zohoAccessJSON.access_token} })` 

- get zoho contact by zoho contact id: `fetch(`https://desk.zoho.com/api/v1/contacts/${contact_id}/tickets`, { method: 'GET', headers:{"Authorization": "Zoho-oauthtoken " + zohoAccessJSON.access_token} })`

**Comment by ardeay** [comment]
@giseleblair @bltarkany I added a todo for a wireframe, @bltarkany did you make one you can paste in here?

**Comment by bltarkany** [comment]
![image](https://user-images.githubusercontent.com/50595614/190494407-27321917-6804-4f93-bf3e-2ecbcd175778.png)
![image](https://user-images.githubusercontent.com/50595614/190494424-1c2fe6a2-6a4c-4d51-bbba-e9dee35d101a.png)
