### ISSUE TITLE
[MOBILE] Headless CMS (tech overview) - images on mobile

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#89]
Switch the following images to be on top of their text ONLY on mobile:

- Header image
- Key features image
- Featured image (next to "features list")

**Comment by darwin808** [comment]
![Screenshot_2022-03-17_04-14-56](https://user-images.githubusercontent.com/71545960/158682605-d3640d0f-3958-45f1-8394-7f583dc4506f.png)
![Screenshot_2022-03-17_04-15-07](https://user-images.githubusercontent.com/71545960/158682615-4655af80-4e56-46e8-be76-9f32c22bc292.png)
![Screenshot_2022-03-17_04-15-16](https://user-images.githubusercontent.com/71545960/158682617-01635d74-5fd5-4670-9b27-a8370a496d07.png)
