### ISSUE TITLE
Instances: Domains Tab

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#892]

**Comment by bltarkany** [comment]
current build- working with Darwin to get commit unblocked:


![Image](https://user-images.githubusercontent.com/50595614/187918632-0586ae3f-ee1e-4387-b1bd-8404d537e790.png)



![Image](https://user-images.githubusercontent.com/50595614/187918657-8a178b5a-d5cb-4c4a-9b54-58ad8718d710.png)
