### ISSUE TITLE
Port Teams Page functionality

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#906]
Should live under /teams in nextjs project

See https://accounts.zesty.io/teams

![Image](https://user-images.githubusercontent.com/729972/187434149-e96327a2-be15-419e-b0c1-6c549be17cea.png)

**Comment by bltarkany** [comment]
Adding pending team invites to the layout and including team assigned instances in the team cards:
![image](https://user-images.githubusercontent.com/50595614/187466219-34908b8d-1bb2-435c-89d9-dc800e2ff184.png)
![image](https://user-images.githubusercontent.com/50595614/187466279-609341bb-97f1-49f5-802d-896331dafe09.png)
