### ISSUE TITLE
Blog article fixes

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/nextjs-website#915]
Can we please update the following on all of our blog articles:

- Title on the page needs to be tagged as an H1 - right now it's not showing up as anything. Please apply this to all articles.
![image](https://user-images.githubusercontent.com/101665566/187544325-99f3a324-8f03-4010-af38-ca830e794f3d.png)

- H2 and H3 sizing is off - please apply the following:
- H2: 26 pt
- H3: 22 pt

**Comment by jomarmontuya** [comment]
https://github.com/zesty-io/website/pull/927
