### ISSUE TITLE
Instances: Teams view

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/nextjs-website#917]
Only teams that are added to the instance should be here - using the Get All Instance's Teams endpoint (https://accounts-api.zesty.org/?version=latest#e507fba0-a188-4d93-8bf5-10473487d677). Additionally, it only needs to have the ability to be deleted here. No need for edit or invite -- that should be done on the teams' page:
![image](https://user-images.githubusercontent.com/50595614/187546300-202d0deb-1261-4fae-bf04-bdf45877954d.png)

the Add Team button should hit the Add Team to Instance endpoint here(https://accounts-api.zesty.org/?version=latest#01889bbf-4529-4e6e-a8d0-193172837719)
![image](https://user-images.githubusercontent.com/50595614/187547512-b847a123-fb42-4908-addf-45459123ad9d.png)

teams should also have an area that describes the role&permissions access because you assign a team a role:
![image](https://user-images.githubusercontent.com/50595614/187548473-a9e46891-62a7-43c2-a1c2-6b8123ac81c9.png)

**Comment by ardeay** [comment]
Also see https://github.com/zesty-io/website/issues/906
