### ISSUE TITLE
Accounts Emails: Password reset accept page, Invite URL 

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#925]
Ensure accounts emails are re-routed to the new accounts url.

Please comment the new url structure.

**Comment by ardeay** [comment]
@shrunyan when new accounts switches over at the end of sept, we will need some of the accounts emails updated. Can you have @zesty-io/back-end-developers have a PR ready. URLs will be commented here

**Comment by glespinosa** [comment]
The structure I'll be using in accounts will be: 
/login/reset-password-confirm
and I will just be copying the pattern of query params on old accounts url
?address=gian.espinosa%40zesty.io&token=7rxf0t6x1ng4hxmjzd771f8gr483vv75t4lg1dt4
