### ISSUE TITLE
Move user and instances dropdown to global nav

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#952]
When you click User, instead of going straight to profile, provide a dropdown with actions including logout.

**Comment by ardeay** [comment]
Follow github style flyout

logged in as your@email.com
my profile
security
preferences
---
logout

![Image](https://user-images.githubusercontent.com/729972/188670342-b6f9e7f9-37ea-41ef-92d6-9db88c436ee4.png)
