### ISSUE TITLE
Add dropdown to filter by Ecosystem

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#954]

**Comment by bltarkany** [comment]
GET All ecosystems - endpoint:
https://accounts-api.zesty.org/?version=latest#750eb50b-c53c-44aa-aa4a-b0b1199fb4bf


![Image](https://user-images.githubusercontent.com/50595614/189145543-a9ccadbe-065e-4444-aa4f-505c8967e437.png)



![Image](https://user-images.githubusercontent.com/50595614/189145588-763c63e9-c194-4b50-b091-ae7e95145b60.png)
