### ISSUE TITLE
Top Bar Navigation Additions

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#965]
To left:
Marketplace

On right

- Developer docs as a dropdown

> -  - Guide sand Docs
> -  - Node SDK
> -  - Instance API
> -  - Accounts API
> -  - Auth API
> -  - Media API
> -  - Fetch Wrapper 
> -  - Status status.zesty.io
> -  - https://github.com/zesty-io/fetch-wrapper
> -  - Parsley

- Toggle between light and dark
- Instance Dropdown
- User Avatar dropdown

**Comment by darwin808** [comment]
@giseleblair 

marketplace is this a button to replace the breadcrumbs? 

![image](https://user-images.githubusercontent.com/71545960/189041923-e2477738-8572-48fb-9ff6-0551075afb9c.png)
