### ISSUE TITLE
Error on Getting the team members on Teams Tab when not instance owner

### ISSUE THREAD

**Issue by darwin808** [zesty-io/nextjs-website#990]
# Error on Getting the team members on Teams Tab when not instance owner

example endpoint 

` https://accounts.api.zesty.io/v1/teams/65-ea85e0b1d7-5km7b8/users `

### success

![image](https://user-images.githubusercontent.com/71545960/189676649-ce4fa61f-ac68-40ac-b4ce-8ed1491efc2a.png)

### error

![image](https://user-images.githubusercontent.com/71545960/189676383-ad11d955-01c8-4755-9894-6b2cf69d0a06.png)

**Comment by bltarkany** [comment]
@darwin808 the endpoint that is used to get the users on a team in accounts is the GET **Get Instance Users With Roles** /instances/users/roles endpoint - which will return a key value pair called `teamZUID` if the user is added to the instance by the a team:
https://accounts-api.zesty.org/?version=latest#b440898f-c658-4f0f-abca-9f0b256c0eb9

For example on the zesty.pw instance you can see the results for the output - check index 8 in the preview:
the endpoint hit in network tab:
https://accounts.api.zesty.io/v1/instances/8-f48cf3a682-7fthvk/users/roles

![image](https://user-images.githubusercontent.com/50595614/189748406-78ebe890-a5e0-4df3-8c68-970f06682cc0.png)
